Change download link/version for Boost v 1.76.0
XRPLF/xrpl-dev-portal pull request #1084
Opened 2021-05-24 11:38 UTC by alloynetworks

Update the download links and change the latest available Boost version from 1.71 to 1.75

2021-05-24 14:11 UTC, mDuo13 commented
I believe @seelabs found [some minor incompatibilities with Boost 1.76](https://github.com/ripple/rippled/pull/3819) so we might want to suggest Boost 1.75 for now. And yes, this should be ported to all the build instructions.

(Interestingly: the link checker picked up on this from the macOS build instructions, where it's actual hyperlink and not just text, but I didn't realize until now that it applies to all the builds.)

2021-05-24 14:43 UTC, alloynetworks commented
Are the incompatibilities only in the tests? @seelabs ?

2021-05-29 21:41 UTC, SirJosh1987 approved these changes

2021-06-02 20:05 UTC, mDuo13 commented
I checked with @seelabs and confirmed that Boost 1.76 is indeed not compatible with rippled 1.7.2 or earlier. So Boost 1.75.0 is the recommended version for building, though any version from 1.70.0–1.75.0 should work.

2021-06-14 19:35 UTC, mDuo13 requested changes
I noticed a couple places it still said 1.75.0. I also suggested a rewrite of one of the paragraphs that was getting a little hard to follow.

If you don't mind, I'd like to take it from here to apply the same changes to the other build instructions too.

2021-06-14 19:35 UTC, mDuo13 commented on content/tutorials/manage-the-rippled-server/installation/build-run-rippled-ubuntu.md
> +      6. Set the environment variable `BOOST_ROOT` to point to the new `boost_1_76_0` directory. It's best to put this environment variable in your `.profile`, or equivalent, file for your shell so i
```suggestion
      6. Set the environment variable `BOOST_ROOT` to point to the new `boost_1_75_0` directory. It's best to put this environment variable in your `.profile`, or equivalent, file for your shell so it's automatically set when you log in. Add the following line to the file:
```

2021-06-14 19:35 UTC, mDuo13 commented on content/tutorials/manage-the-rippled-server/installation/build-run-rippled-ubuntu.md
> +              export BOOST_ROOT=/home/my_user/boost_1_76_0
```suggestion
              export BOOST_ROOT=/home/my_user/boost_1_75_0
```

2021-06-14 19:35 UTC, mDuo13 commented on content/tutorials/manage-the-rippled-server/installation/build-run-rippled-ubuntu.md
> +    Version 1.7.0 and higher of `rippled` requires Boost version 1.70.0 or higher. Because Boost version 1.70.0 or higher isn't available in the Ubuntu 18.04 (or 16.04) software repositories, you mus
```suggestion
    Version 1.7.0 of `rippled` requires the Boost library and is compatible with Boost versions 1.70.0 to 1.75.0. The Ubuntu 18.04 (or 16.04) software repositories don't have a compatible Boost version, so you must compile it yourself. The following examples use Boost 1.75.0.
```

2021-06-15 07:19 UTC, alloynetworks commented
> I noticed a couple places it still said 1.75.0. I also suggested a rewrite of one of the paragraphs that was getting a little hard to follow.
> 
> If you don't mind, I'd like to take it from here to apply the same changes to the other build instructions too.

I think that makes sense!

2021-06-16 18:44 UTC, merged