Add details for SignerWeight and SignerQuorum
XRPLF/xrpl-dev-portal pull request #1194
Opened 2021-10-12 16:08 UTC by DennisDawson

Per https://github.com/XRPLF/xrpl-dev-portal/issues/685, add some detail and description around the SignerWeight and SignerQuorum properties.

2021-10-12 20:29 UTC, mDuo13 requested changes
This is a good start. I left a couple specific suggestions for things to tweak, and I had some other more general comments:

- Can you look over the whole file and apply some more consistency around the use of "SignerList" vs "signer list"?
- The example with the CEO/directors is a good one, but I'd like to see some additional examples, to demonstrate the flexibility of the system so people don't get stuck with a single idea of how it should be used. Here are some more ideas:
    - A shared account where any one any of several people could approve any transaction? (say, quorum of 1 with 5 signers, each with a weight of 1)
    - An important account—for example, the issuer of an issued token—where _all_ the signers have to approve changes. (say, quorum of 3 with 3 signers each with a weight of 1)
    - A "backup plan" multi-signing list where the account owner normally uses their regular key (not multi-signing) to authorize transactions, but adds a signer list containing 3 friends (quorum of 3, 3 signers, each weight 1) so that if they ever lose their own private key they can ask their friends to multi-sign a transaction to replace the regular key.
- It may also be worth mentioning as a reminder in some of these examples that the master key should be disabled (and no regular key configured) so that multi-signing is the _only_ way of authorizing transactions on some of these accounts. Obviously that doesn't apply to the "backup plan" example.

2021-10-12 20:29 UTC, mDuo13 commented on content/concepts/payment-system-basics/accounts/multi-signing.md
>  Before you can multi-sign, you must create a list of which addresses can sign for you.
So, this is a preexisting problem in the documentation, but I noticed that we're mixing and matching the terms "SignerList" and "signer list" in the following paragraphs (and probably elsewhere—sorry, that's my bad). 

As a convention, I've been trying to refer to [objects in the ledger state](https://xrpl.org/ledger-object-types.html) in title case matching the code name for the object—Escrow, Offer, etc.¹—so let's use introduce the term SignerList here and use it consistently throughout.

```suggestion
Before you can multi-sign, you must create a list of which addresses can sign for you. This list is stored in the ledger as a SignerList.
```


¹ RippleState is the exception because it's confusing. We usually talk about "trust lines", which are often described as being unilateral, but the storage format (RippleState) is a bilateral format (i.e. if you have a unilateral trust line you really have a bilateral RippleState with one half default/disabled; and if you have a matching pair of incoming/outgoing trust lines they're represented as a single shared RippleState object. Like I said, it's confusing.)

2021-10-12 20:29 UTC, mDuo13 commented on content/concepts/payment-system-basics/accounts/multi-signing.md
> +The SignerQuorum value is the minimum SignerWeight total required to authorize a transaction. The SignerQuorum value must be attainable. The SignerQuorum must be greater than 0 but less than or equal
> or all transactions fail.

This sounds dramatic, and I think it's not what you mean here.

It's not possible to set a SignerQuorum that's higher than the sum of weights in a list. If you tried, the SignerListSet transaction to define such a quorum would fail. Since that's the case, I think the sentence is clearest if we just remove this bit.

```suggestion
The SignerQuorum value is the minimum SignerWeight total required to authorize a transaction. The SignerQuorum value must be attainable. The SignerQuorum must be greater than 0 but less than or equal to the sum of the SignerWeight values in the SignerList.  
```

2021-10-12 20:29 UTC, mDuo13 commented on content/concepts/payment-system-basics/accounts/multi-signing.md
> +For example, you might assign a SignerQuorum of 3 to to an account. You assign your CEO a SignerWeight of 3, Vice Presidents a SignerWeight of 2, and Directors  a SignerWeight of 1. To approve a tran
```
and Directors  a SignerWeight of 1.
```

Extra space after "Directors" and I think it would be good to clarify that you mean a weight of 1 _each_ for some number of directors.
```suggestion
For example, you might assign a SignerQuorum of 3 to to an account. You assign your CEO a SignerWeight of 3, Vice Presidents a SignerWeight of 2, and three Directors a SignerWeight of 1 each. To approve a transaction for this account requires the approval of 3 Directors (total weight of 3), 1 Vice President and 1 Director (total weight of 3), 2 Vice Presidents (total weight of 4), or the CEO (total weight of 3). The SignerWeight and SignerQuorum allow you to set an appropriate level of scrutiny for each transaction, based on the relative trust and authority relegated to responsible members of your organization. 
```

> The SignerWeight and SignerQuorum allow you to set an appropriate level of scrutiny for each transaction

I'm not sure what it means to set a level of scrutiny for each transaction. I guess maybe what you're getting at is that it lets you set how many people must look at the transaction before approving it?

2021-10-12 22:32 UTC, DennisDawson commented on content/concepts/payment-system-basics/accounts/multi-signing.md
>  Before you can multi-sign, you must create a list of which addresses can sign for you.
I've updated the text to address these suggestions.

2021-10-12 22:33 UTC, DennisDawson commented on content/concepts/payment-system-basics/accounts/multi-signing.md
> +The SignerQuorum value is the minimum SignerWeight total required to authorize a transaction. The SignerQuorum value must be attainable. The SignerQuorum must be greater than 0 but less than or equal
I've updated the doc to address these suggestions.

2021-10-12 22:33 UTC, DennisDawson commented on content/concepts/payment-system-basics/accounts/multi-signing.md
> +For example, you might assign a SignerQuorum of 3 to to an account. You assign your CEO a SignerWeight of 3, Vice Presidents a SignerWeight of 2, and Directors  a SignerWeight of 1. To approve a tran
I've updated the doc to address these suggestions.

2021-10-13 00:05 UTC, mDuo13 approved these changes
Looking good. I left a couple more minor suggestions but they're not urgent.

Also, I think I've fixed the issues with the CI lately, optionally, if you rebase this PR onto the latest master branch, we can test having it staged and having the link checker run automatically. Happy to help walk you through the commands to do that if you'd like.

2021-10-13 00:05 UTC, mDuo13 commented on content/concepts/payment-system-basics/accounts/multi-signing.md
> +In each of the previous three use cases, you would disable the master key without configuring a regular key, so that multi-signing is the only way of authorizing transactions.
Here's an appropriate link for people who want more context:

```suggestion
In each of the previous three use cases, you would disable the master key without configuring a regular key, so that multi-signing is the only way of [authorizing transactions](transaction-basics.html#authorizing-transactions).
```

2021-10-13 00:05 UTC, mDuo13 commented on content/concepts/payment-system-basics/accounts/multi-signing.md
> +There might be a scenario where you create a multi-signing list as a "backup plan." The account owner normally uses a regular key for their transactions (not a multi-signing key). For safety, the own
The bit about "then the owner sets" make it seem like it's a second step, but it happens at the same time, so I suggest rephrasing it as follows:

```suggestion
There might be a scenario where you create a multi-signing list as a "backup plan." The account owner normally uses a regular key for their transactions (not a multi-signing key). For safety, the owner adds a SignerList containing 3 friends, each with a weight of 1, and a SignerQuorum of 3. If the account owner were to lose the private key, they can ask their friends to multi-sign a transaction to replace the regular key.
```

2021-10-20 23:01 UTC, merged