Improve Docs for Decentralized Exchange
XRPLF/xrpl-dev-portal pull request #1357
Opened 2022-03-05 00:49 UTC by mDuo13

- Add a new concept article describing the DEX at a high level, including a new diagram of processing a trade.
    - The `.uxf` file is the [Umlet](https://www.umlet.com/) source file for the diagram. The `.svg` file is the exported version of the same thing.
- Rewrite the "Offers" concept page to better complement the DEX concept page and hopefully read more clearly without going immediately into technical details.
- Update the OfferCreate transaction reference slightly to add a list of error cases and improve wording a bit, including linking to the new articles.

2022-03-11 23:21 UTC, amarantha-k requested changes

2022-03-11 23:21 UTC, amarantha-k commented on content/concepts/decentralized-exchange/decentralized-exchange.md
> +The XRP Ledger's has possibly the world's oldest _decentralized exchange_ (sometimes abbreviated "DEX"), operating continuously since the XRP Ledger's launch in 2012. The exchange allows users to buy
The XRP Ledger has ...

2022-03-11 23:21 UTC, amarantha-k commented on content/concepts/decentralized-exchange/decentralized-exchange.md
> +**Caution:** Any can [issue a token](issue-a-fungible-token.html) with any currency code or ticker symbol they want and sell it in the decentralized exchange. Always pay attention to the issuer of an
Anyone can [issue a token](issue-a-fungible-token.html) with any currency code or ticker symbol they want and sell it in the decentralized exchange. Always perform due diligence before buying a token and pay attention to the issuer of the token. Otherwise, you might give up something of value and receive worthless tokens in exchange.

2022-03-11 23:21 UTC, amarantha-k commented on content/concepts/decentralized-exchange/decentralized-exchange.md
> +The above diagram shows an example trade in the decentralized exchange. In this example, a trader named Tran places an Offer to buy 100 tokens with the currency code FOO issued by a fictional busines
Replace "all of the following things happen" with "the following things happen"

2022-03-11 23:21 UTC, amarantha-k commented on content/concepts/decentralized-exchange/decentralized-exchange.md
> +As a decentralized system, the XRP Ledger does not have any information on the actual people and organizations behind the [accounts](accounts.html) involved in trading. Therefore, the ledger itself c
Suggestion: Change "help issuers to follow these types of rules" to "help issuers comply with relevant laws and regulations" ?

2022-03-11 23:21 UTC, amarantha-k commented on content/concepts/decentralized-exchange/offers.md
> +- be the token's issuer.
Be

2022-03-11 23:21 UTC, amarantha-k commented on content/concepts/decentralized-exchange/offers.md
> +**To sell XRP,** you must hold enough XRP to meet all the [reserve requirements](reserves.html), including the reserve for the Offer object to be placed in the ledger and the trust line to hold the t
- non-zero
- "setting aside the amounts for " -> "setting aside the amount for"

2022-03-11 23:21 UTC, amarantha-k commented on content/concepts/decentralized-exchange/offers.md
>  Trust lines limits protect you from receiving more of a token as payment than you want. Offers can go beyond those limits because they are an explicit statement of how much of the token you want.
Trust line limits?

2022-03-11 23:21 UTC, amarantha-k commented on content/references/protocol-reference/transactions/transaction-types/offercreate.md
> +## Error Cases
Suggest presenting this information as a table with error codes and description.

2022-03-12 00:20 UTC, mDuo13 commented
Applied the requested changes. Also, [46e43a2](https://github.com/XRPLF/xrpl-dev-portal/pull/1357/commits/46e43a2656ead7cdbd6a765205b98ca348cfe409) fixes some small issues with the Known Amendments page that came up in this process (see commit message for details).

2022-03-21 05:37 UTC, amarantha-k approved these changes
LGTM

2022-03-21 15:11 UTC, merged