Remove duplicate definition for the term sidechain
XRPLF/xrpl-dev-portal pull request #1381
Opened 2022-03-28 18:02 UTC by amarantha-k

2022-03-28 18:09 UTC, mvadari approved these changes

2022-03-28 18:16 UTC, mDuo13 requested changes
Lists should always have some sort of order to them; I suggest putting these terms in alphabetical order. If it were possible to introduce simpler concepts and build up to the other ones, that would define a good order to introduce terms in. Unfortunately, all the terms here are defined in terms of the other terms here, so there's no clear learning order. Maybe they could be reworded more to clarify that?

At least having them in alphabetical order would make it easier to find the definition you're looking for and would have made it obvious that there was a duplicate entry.

Also, I noticed a few cases where treatment of "mainchain" and "sidechain" (with or without a space was inconsistent and tagged those.

2022-03-28 18:16 UTC, mDuo13 commented on content/concepts/consensus-network/federated-sidechains.md
>  _Mainchain_: The blockchain where assets originate and where assets are held while being used on the side chain. For most sidechains, the mainchain is the XRP Ledger Mainnet, Testnet, or Devnet.
```suggestion
_Mainchain_: The blockchain where assets originate and where assets are held while being used on the sidechain. For most sidechains, the mainchain is the XRP Ledger Mainnet, Testnet, or Devnet.
```

2022-03-28 18:16 UTC, mDuo13 commented on content/concepts/consensus-network/federated-sidechains.md
>  _Federator_: A server on the sidechain that listens for triggering transactions on both the main chain and the side chain. Each federator has a signing key associated with it that is used to sign tra
```suggestion
_Federator_: A server on the sidechain that listens for triggering transactions on both the mainchain and the sidechain. Each federator has a signing key associated with it that is used to sign transactions. A transaction must be signed by a quorum of federators before it can be submitted. Federators are responsible for creating and signing valid response transactions, collecting signatures from other federators, and submitting transactions to the mainchain and sidechain.
```

2022-03-29 08:46 UTC, wojake approved these changes
LGTM

2022-03-29 22:32 UTC, amarantha-k commented
@mDuo13 The terms are now in alphabetical order. Looks like you need re-review and approve before this PR can be merged.

2022-03-30 16:02 UTC, wojake requested changes
Why must it be in an alphabetical order? I think the list should be in a relevance order. The easier/basic concepts should be on top of the list and so on...

2022-03-30 17:16 UTC, mDuo13 approved these changes

2022-03-30 21:14 UTC, merged