add comments for tickets issue #1430
XRPLF/xrpl-dev-portal pull request #1431
Opened 2022-07-07 04:14 UTC by lathanbritz

light bit of documentation for good place to use tickets.

2022-07-09 22:47 UTC, intelliot requested changes
Just a suggestion

2022-07-09 22:47 UTC, intelliot commented on content/_code-samples/secure-signing/js/signPayment.js
> +// in place of the sequence number, this is useful when you need multiple signatures.
```suggestion
// For offline signing, you need to know your address's next Sequence number.
// Alternatively, you could use a Ticket in place of the Sequence number.
// This is useful when you need multiple signatures and may want to process transactions out-of-order.
// For details, see: https://xrpl.org/tickets.html
```

2022-07-12 19:26 UTC, mDuo13 approved these changes

2022-07-12 19:31 UTC, intelliot approved these changes

2022-07-12 21:04 UTC, merged