Feat - Developer Funding
XRPLF/xrpl-dev-portal pull request #1482
Opened 2022-08-29 22:16 UTC by JakeatRipple

2022-08-29 23:01 UTC, mDuo13 requested changes
We'll need to coordinate with #1476 to make sure whoever merges second doesn't clobber the (S)CSS updates, but otherwise this looks mostly good. I noticed one little bug in the animation and a couple opportunities for cleaning up the code.

2022-08-29 23:01 UTC, mDuo13 commented on dactyl-config.yml
> +
Add the untranslated page to the Japanese target just so it's not a missing link there.

```suggestion
            - en
            - ja

```

2022-08-29 23:01 UTC, mDuo13 commented on template/page-funding.html.jinja
> +                <!-- end col 2 -->
This should probably be a for loop, right? That should also make it easier to fix some nitpicks with the markup, like:

- For the `<p class="">`, omit the empty attribute
- Close the image tags XHTML style. Also, a change that'll matter for Redocly: technically the src attribute isn't supposed to be omitted so you can provide an empty data URL to satisfy browsers that are picky about that `<img id="funding-04" src="data:," />`

Same goes for the other funding lists below.

2022-08-29 23:01 UTC, mDuo13 commented on template/page-funding.html.jinja
> +            <a class="btn btn-primary btn-arrow btn-arrow-out" target="_blank" href="https://xrplgrants.org/">{% trans %}Visit XRPL Grants{% endtrans %}</a>
The `btn-arrow` and `btn-arrow-out` classes are clashing and resulting in weird jaggedy movement on the hover animation. Removing `btn-arrow` here fixes it, making the arrow behave the same as the "Learn more" for the Creator Fund link below:

```suggestion
            <a class="btn btn-primary btn-arrow-out" target="_blank" href="https://xrplgrants.org/">{% trans %}Visit XRPL Grants{% endtrans %}</a>
```

2022-08-30 22:21 UTC, JakeatRipple commented on template/page-funding.html.jinja
> +                <!-- end col 2 -->
Yes I think some loop could work but have not figured out an easy way to do it.  The staggered on desktop changes order from the mobile. 

I can look into it further but for the time being I fixed those other issues so it wont hold up the PR.

2022-08-30 22:48 UTC, mDuo13 approved these changes
Looks like the build failure is because the link checker doesn't understand the new `data:,` URIs, which, go figure. You make one tool happy and it makes the other tool upset. They still display correctly to end-users, which is what really matters. :+1:  to this PR.

2022-08-30 22:54 UTC, merged