DGE-94-Cryptographic-Key-Derivation
XRPLF/xrpl-dev-portal pull request #1514
Opened 2022-09-13 13:07 UTC by interc0der

Bounty pull request for 0031 - DGE-94-Cryptographic-Key-Derivation

2022-09-15 20:22 UTC, jonathanlei commented
Good start of implementation using existing xrpl-js tools, could you add some tests?

2022-09-27 21:27 UTC, JST5000 commented
For context this is referring to the xrpl.js code snippets bounty: https://github.com/XRPLBounties/Proposals/blob/main/bounties/0031%20JavaScript%20Code%20Samples.md

2022-09-29 21:08 UTC, JST5000 commented on content/_code-samples/key-derivation/js/derive.js
> +const entropy= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
nit:
```suggestion
const entropy = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
```

2022-09-29 21:14 UTC, JST5000 commented
For this bounty the goal is to have feature parity with these snippets so they can be used interchangeably depending on what language the new reader is most comfortable with: https://github.com/XRPLF/xrpl-dev-portal/tree/master/content/_code-samples/key-derivation/py

And specifically, the snippets are supposed to give a concrete way to understand these high-ish level concepts: https://xrpl.org/cryptographic-keys.html#key-derivation

So instead of using the client library to abstract away the details of the encode/decode, it's actually important to step through it and add comments explaining the intent. (The python one has some of those comments, and the high level concept also may have some useful things to point out in the code)

2022-09-29 22:40 UTC, JST5000 requested changes
See above comment

2022-10-13 21:45 UTC, JST5000 commented
Hey @interc0der I'm closing this PR as we have accepted a different submission for this bounty (https://github.com/XRPLF/xrpl-dev-portal/pull/1507).

2022-10-13 21:45 UTC, closed without merging