Update source repo URL
XRPLF/xrpl-dev-portal pull request #1532
Opened 2022-09-29 15:58 UTC by amarantha-k

2022-09-29 17:22 UTC, DennisDawson approved these changes
Changes look good to me.

2022-09-29 21:29 UTC, mDuo13 requested changes

2022-09-29 21:29 UTC, mDuo13 commented on content/contributing/contribute-code.md
> +| Repository             | <[https://github.com/XRPLF/rippled](https://github.com/XRPLF/rippled)>                |
This was already an [autolink](https://daringfireball.net/projects/markdown/syntax#autolink), so there's no need to mix link styles (and doing both like this results in extra symbols)

```suggestion
| Repository             | <https://github.com/XRPLF/rippled>                |
```

2022-10-18 00:30 UTC, mDuo13 approved these changes

2022-10-18 00:30 UTC, merged