Search bar UI change
XRPLF/xrpl-dev-portal pull request #1610
Opened 2022-11-29 05:37 UTC by jonathanlei

Change DocSearch3 UI according to design.

2022-11-29 18:18 UTC, amarantha-k commented
Re-running preview build job as the PR preview link was returning a 404.

2022-11-29 19:01 UTC, jonathanlei commented
> Re-running preview build job as the PR preview link was returning a 404.

usually it takes a while for preview to show up

2022-11-30 22:45 UTC, amarantha-k commented
@jonathanlei After selecting a search result, the page refreshes and the top menu is misaligned in the desktop view. 
https://user-images.githubusercontent.com/13425257/204924017-9e04c490-85e3-46b6-b7af-5a10ee1ed989.mov

2022-11-30 23:11 UTC, jonathanlei commented
> @jonathanlei After selecting a search result, the page refreshes and the top menu is misaligned in the desktop view. https://user-images.githubusercontent.com/13425257/204924017-9e04c490-85e3-46b6-b7af-5a10ee1ed989.mov

@amarantha-k that's because it redirected to the current site (xrpl.org) instead of the preview site :)

2022-12-01 05:48 UTC, amarantha-k commented
> > @jonathanlei After selecting a search result, the page refreshes and the top menu is misaligned in the desktop view. https://user-images.githubusercontent.com/13425257/204924017-9e04c490-85e3-46b6-b7af-5a10ee1ed989.mov
> 
> @amarantha-k that's because it redirected to the current site (xrpl.org) instead of the preview site :)

Oops - my bad, totally missed that!

2022-12-01 20:53 UTC, mDuo13 requested changes
Can you bump the version number of the generated CSS file? If we deploy changes like this to the production site, then anyone who has the current (v12) version cached won't see the differences right away. (They'll have to refresh w/o cache, or wait for the cached version to expire.)

2022-12-01 20:53 UTC, mDuo13 commented on styles/xrpl.css
> +  background-color: #232325;
This file (and the corresponding `xrpl.css.map`) shouldn't be committed to the repo; I missed that while reviewing #1581. Please delete them.

2022-12-01 20:53 UTC, mDuo13 commented on styles/_colors.scss
> +$black-60: #454549;
These are just aliases for `$gray-100, $gray-400, and $gray-600`, right? Can we do without them? If not, I suggest explicitly defining them in terms of the original name, like this:

```suggestion
$black-10: $gray-100;
$black-40: $gray-400;
$black-60: $gray-600;
```

2022-12-01 21:34 UTC, mDuo13 approved these changes

2022-12-01 21:35 UTC, merged