Descriptive list of types in Transaction Types
XRPLF/xrpl-dev-portal pull request #1790
Opened 2023-03-03 20:00 UTC by zgrguric

As amendments added more types, it would be better to link to /transaction-types.html page with ellipsis.

2023-03-15 05:21 UTC, intelliot approved these changes

2023-04-05 15:33 UTC, mDuo13 requested changes

2023-04-05 15:33 UTC, mDuo13 commented on content/references/protocol-reference/transactions/transaction-common-fields.md
> +| `TransactionType`    | String           | UInt16            | _(Required)_ The type of transaction. Valid [types](transaction-types.html) include: `Payment`, `OfferCreate`, `OfferCancel`, `TrustSet
I agree with the premise here, but if anything I don't think you take it far enough. If you're going to abbreviate it, let's trim it to three example types and leave the rest to if you click through.

```suggestion
| `TransactionType`    | String           | UInt16            | _(Required)_ The type of transaction. Valid [transaction types](transaction-types.html) include: `Payment`, `OfferCreate`, `TrustSet`, and many others. |
```

2023-04-05 18:06 UTC, zgrguric commented
Same should be done in `transaction-common-fields.ja.md` but I'm not fluent in Japanese unfortunately.

2023-04-11 17:11 UTC, mDuo13 approved these changes

2023-04-17 18:36 UTC, merged