updates pencil banner for xrpl grants
XRPLF/xrpl-dev-portal pull request #1802
Opened 2023-03-07 16:29 UTC by AKCodez

2023-03-07 16:31 UTC, AKCodez commented
@jonathanlei @mDuo13 PR ready for review ASANA ticket - https://app.asana.com/0/1203394966732942/1204092866350891

2023-03-10 00:06 UTC, mDuo13 requested changes

2023-03-10 00:06 UTC, mDuo13 commented on dactyl-config.yml
> +    - carbon-calculator.html
Please remove this line; it's addressed more properly by #1808 instead. Known broken links are for things that we can't fix the "right" way.

2023-03-11 00:15 UTC, mDuo13 approved these changes

2023-03-11 00:15 UTC, merged