[DO NOT MERGE] Docs.html page update
XRPLF/xrpl-dev-portal pull request #1866
Opened 2023-04-10 23:18 UTC by JST5000

This updates the top-level documentation page with a new format. 

Opening this PR as a draft for now in order to allow people to see a build-preview for the work so far to get feedback, and to make it easier for others to combine other pieces of the work into it.

2023-04-20 18:32 UTC, ckniffen commented on styles/yarn.lock
>  "@babel/code-frame@^7.0.0":
What was the reason for alll of these version bumps?  Might make sense for this to be in a separate PR.

2023-04-21 01:16 UTC, ckniffen commented on styles/package.json
> +    "jquery": "^1.9.1",
Should this be a dev dependency? @JST5000

2023-04-26 22:50 UTC, JST5000 commented on styles/package.json
> +    "jquery": "^1.9.1",
I don't think so, no.

2023-04-26 22:53 UTC, JST5000 commented on template/page-docs.html.jinja
> +{% block mainclasses %}landing page-docs-index landing-builtin-bg jackson-identifier {% endblock %}
I'm not sure why this isn't showing up locally for me - but `jackson-identifier` should probably be removed.

2023-04-26 23:52 UTC, JST5000 commented
> File: out/ja/serialization.html Link: [STIssue][]

@mDuo13 do you happen to know why this would be the case? (It seems to be affecting both this PR and @pdp2121's PR here: https://github.com/XRPLF/xrpl-dev-portal/pull/1892 so it seems maybe it's an error on main?)

Meta: How do you normally go about debugging the broken link error?

2023-05-02 20:01 UTC, mDuo13 commented
> > File: out/ja/serialization.html Link: [STIssue][]
> 
> @mDuo13 do you happen to know why this would be the case? (It seems to be affecting both this PR and @pdp2121's PR here: #1892 so it seems maybe it's an error on main?)
> 
> Meta: How do you normally go about debugging the broken link error?

#1894 explains and resolves the STIssue ink error. In cases like that where there's a broken link in master, PRs that were branched off while the issue was active will show the error unless they're rebased or have a reverse-merge, but even if you do neither of those things they're safe to merge to master.

For debugging broken links, if the change doesn't come from or link to one of the files modified in the file—including via includes—then I check to see if it's a case where a broken link snuck into master, like this one. Otherwise, you can look at the HTML source and search (as in, ctrl-f) for the reported text of the link. In some cases, like this one, `[STIssue][]` being reported as a broken link means that the page used Markdown's ["reference link" syntax](https://www.markdownguide.org/basic-syntax#reference-style-links) but the reference wasn't matched—basically, you tried to reference something without a definition—so the bracket syntax shows up directly in the final page text.

2023-05-11 06:18 UTC, Silkjaer commented
This really looks great. Great update to have better entries into the documentation.

2023-05-11 20:18 UTC, mDuo13 requested changes
Overall, looks great. I dug a bit deeper into the changes and requested a lot of little nitpicky fixes, but in general it looks good.

2023-05-11 20:18 UTC, mDuo13 commented on template/page-docs.html.jinja
> +    <a href="./docs-index.html" class="external-link ml-auto">See full documenation index <i aria-hidden="true" class="fa fa-external-link"></i></a>
Typo. Also, translation tags.

```suggestion
    <a href="./docs-index.html" class="external-link ml-auto">{% trans %}See full documentation index{% endtrans %} <i aria-hidden="true" class="fa fa-external-link"></i></a>
```

2023-05-11 20:18 UTC, mDuo13 commented on template/page-home.html.jinja
> +          "href": "docs.html"},
```suggestion
          "href": "non-fungible-tokens.html"},
```

2023-05-11 20:18 UTC, mDuo13 commented on template/page-home.html.jinja
> +          "description":  _("Lower fees, faster transactions, and custom token functionality make the XRPL ideally suited for building an ecosystem for NFTs. Explore <a href='docs.html'>proposed stan
Probably we should at some point change this whole block to be a different upcoming feature rather than highlighting NFTs, but for now, we should not link "proposed standards" for something that's in use now.

```suggestion
          "description":  _("Lower fees, faster transactions, and custom token functionality make the XRPL ideally suited for building an ecosystem for NFTs. Explore the XRP Ledger's NFT capabilities."),
```

2023-05-11 20:18 UTC, mDuo13 commented on template/page-docs.html.jinja
> +    <div class="card video-image flat-card">
As we discussed separately, the `video-image` class should not be used for these

2023-05-11 20:18 UTC, mDuo13 commented on styles/_docs.scss
I'm really nitpicking here, but calling this page `_docs.scss` makes it unclear if it's referring to the actual ("leaf") documentation pages, or the "Docs" landing page. Renaming it to `_docs-landing.scss` or `_docs-home.scss` would be clearer.

2023-05-11 20:18 UTC, mDuo13 commented on styles/_docs.scss
> +    color: #000
There are a bunch of color name variables defined in `_colors.scss`. Wherever possible, please use those instead of hard-coding color values into the SCSS; that way, if we tweak the color palette, the changes automatically update throughout the styles. (For example, in the past, we changed from "pure black" to "off-black" for some things.)

```suggestion
    color: $black
```

2023-05-11 20:18 UTC, mDuo13 commented on styles/_docs.scss
> +    color: #fff;
```suggestion
    color: $white;
```

2023-05-11 20:18 UTC, mDuo13 commented on styles/_docs.scss
> +    color: #E0E0E1;
```suggestion
    color: $gray-200;
```

2023-05-11 20:18 UTC, mDuo13 commented on styles/_docs.scss
> +      text-decoration-color: #9A52FF;
```suggestion
      text-decoration-color: $purple;
```

2023-05-11 20:18 UTC, mDuo13 commented on styles/_docs.scss
> +      text-decoration-color: #9A52FF;
```suggestion
      text-decoration-color: $purple;
```

2023-05-11 20:18 UTC, mDuo13 commented on styles/_pages.scss
> -    background-image: url(../img/backgrounds/bg-docs.png);
In cases where this PR removes the last use of a particular image (as best I can tell, `bg-docs.png` is only used this once), please remove the corresponding file so the repo doesn't accumulate unused files.

2023-05-11 20:18 UTC, mDuo13 commented on img/backgrounds/docs-splash.svg
The way the folder structure is intended to work is that the top-level `img/` folder is for images used in the documentation _contents_, and the `assets/img/` folder is for images used in the templates. (That's not consistently how it's been used, but I would like to try and get closer to the ideal rather than farther.) So, preferably, please move this to `assets/img/backgrounds/` and update the SCSS accordingly.

2023-05-11 20:18 UTC, mDuo13 commented on assets/css/devportal2022-v16.css
When making changes like this that add new styles, we like to increment the version number to prevent the case where users' browsers load the CSS file from cache, causing the page to display incorrectly. (It's not necessary when only removing styles.)

To do that:
1. Modify the `styles/package.json` file to change the version number in all three builds. For example, change it to `devportal2022-v17.css`
2. Rebuild the CSS (`yarn run build-css` from within `styles/`)
3. Delete the old CSS file (v16) from git and add the new one (v17) (`git rm assets/css/devportal2022-v16.css && git add assets/css/devportal2022-v17.css`)
4. Modify the CSS path in `template/base.html.jinja` on line 55 to match the new version number.

2023-05-11 20:18 UTC, mDuo13 commented on styles/_pages.scss
> +    background-image: url(../../img/backgrounds/docs-splash.svg);
If you move the file as I recommended above, update this path as well.

```suggestion
    background-image: url(../../assets/img/backgrounds/docs-splash.svg);
```

2023-05-11 20:18 UTC, mDuo13 commented on styles/xrpl.scss
> +@import "_docs.scss";
If you rename this file as I recommended above, don't forget to change it here, too.

```suggestion
@import "_docs-home.scss";
```

2023-05-11 20:18 UTC, mDuo13 commented on template/page-docs.html.jinja
> +    <a href="./docs-index.html" class="external-link mr-auto">See full documenation index <i aria-hidden="true" class="fa fa-external-link"></i></a>
Just noted this on the design figma, which this matches, but I don't think this should be styled as an external link, since it doesn't actually take you off-site.

2023-05-11 20:18 UTC, mDuo13 commented on template/page-docs.html.jinja
> +    <h4 class="pb-4">Getting Started</h4>
There are a lot of cases here where new user-facing text isn't marked in `{% trans %}` tags to make it translatable. For consistency and to make it easier on @develoQ or anyone else doing translation, we should update these.

```suggestion
    <h4 class="pb-4">{% trans %}Getting Started{% endtrans %}</h4>
```

I haven't tagged all of them but in general it applies to any user-visible text written directly into the template. (For now, I think we're punting on text in variables/macros.)

2023-05-11 20:18 UTC, mDuo13 commented on template/page-docs.html.jinja
> +          <h5 class="mt-7"> Quickstart to XRP Ledger </h5>
```suggestion
          <h5 class="mt-7">{% trans %}Quickstart to XRP Ledger{% endtrans %}</h5>
```

2023-05-11 20:18 UTC, mDuo13 commented on template/page-docs.html.jinja
> +          <h5 class="mt-7"> Quickstart to XRP Ledger </h5>
```suggestion
          <h5 class="mt-7">{% trans %}Quickstart to XRP Ledger{% endtrans %}</h5>
```

2023-05-11 20:18 UTC, mDuo13 commented on template/page-docs.html.jinja
> +    set devTools = [
I started writing a long thing about how you could dynamically set this in a more translation-friendly way using `pages|selectattr(...)`, but (a) it's very Dactyl-specific, and (b) the dev tools don't actually have blurbs in the config file where you could the (language-appropriate) one, so you'd have to fix that while you're at it.

So, I guess, nevermind. This is good enough.

2023-05-12 07:23 UTC, Silkjaer approved these changes
LGTM!

2023-05-16 22:21 UTC, mDuo13 approved these changes
One minor thing to fix, otherwise this looks good.

2023-05-16 22:21 UTC, mDuo13 commented on template/page-docs.html.jinja
> +        <div class="btn btn-primary btn-arrow-out" id="{{href}}-button">{{ linkText }}</div>
These should be horizontal, not diagonal arrows.

```suggestion
        <div class="btn btn-primary btn-arrow" id="{{href}}-button">{{ linkText }}</div>
```

2023-05-17 21:54 UTC, merged