1st draft nft-storage
XRPLF/xrpl-dev-portal pull request #1868
Opened 2023-04-11 21:13 UTC by DennisDawson

2023-05-01 16:03 UTC, amarantha-k requested changes

2023-05-01 16:03 UTC, amarantha-k commented on content/concepts/tokens/nft-storage.md
> +For a list of cloud storage solutions, the blog post [NFT Payload Storage](https://xrpl.org/blog/2023/nft-payload-storage.html).
```suggestion
See the blog post [NFT Payload Storage](https://xrpl.org/blog/2023/nft-payload-storage.html) for some examples of cloud storage solutions.
```

2023-05-01 16:03 UTC, amarantha-k commented on content/concepts/tokens/nft-storage.md
> +NFTs are created on the block chain. But the payload of the NFT, including media, metadata, and attributes can be stored in a variety of ways, including on-chain, decentralized off-chain, and central
```suggestion
NFTs are created on the blockchain. But the payload of the NFT, including media, metadata, and attributes can be stored in a variety of ways, including on-chain, decentralized off-chain, and centralized off-chain.
```

2023-05-01 16:03 UTC, amarantha-k commented on content/concepts/tokens/nft-storage.md
> +NFTs are created on the block chain. But the payload of the NFT, including media, metadata, and attributes can be stored in a variety of ways, including on-chain, decentralized off-chain, and central
The term "off-chain" doesn't appear to have been used in the XRPL documentation so far; "on/off-ledger" has been used instead.

2023-05-01 18:32 UTC, amarantha-k commented
Noting here for completion - the link to the NFT Metadata blog is proposed and may change.

2023-05-02 19:11 UTC, DennisDawson commented
Note that the accompanying blog post is staged here:
https://github.com/ripple/dev-blog/blob/DennisDawson-nft_storage/content/2023/nft-payload-storage.md

2023-09-06 20:57 UTC, amarantha-k approved these changes

2023-09-06 21:02 UTC, merged