feat: feedback widget from developers modal
XRPLF/xrpl-dev-portal pull request #1892
Opened 2023-04-26 18:19 UTC by pdp2121

Add back feedback widget and fix design:

Dark Mode:
![Screenshot 2023-04-26 at 2 16 12 PM](https://user-images.githubusercontent.com/71317875/234667105-65f9d6e2-aa30-4432-a3c0-0e87eef2fb55.png)
![Screenshot 2023-04-26 at 2 02 44 PM](https://user-images.githubusercontent.com/71317875/234667140-aaf6c6fc-d873-412d-8a7c-e74f779e72df.png)

Light Mode:
![Screenshot 2023-04-26 at 2 13 55 PM](https://user-images.githubusercontent.com/71317875/234667185-c596ccc6-f5b6-466c-8558-b4e5f479d93d.png)
![Screenshot 2023-04-26 at 2 02 12 PM](https://user-images.githubusercontent.com/71317875/234667233-ae27dee3-18be-4253-81f1-1ad69ef8bc8c.png)

2023-04-26 19:58 UTC, pdp2121 commented
Hmm the Preview didn't reflect the changes here

2023-04-27 20:57 UTC, pdp2121 commented
@mDuo13 The preview doesn't work because we are using a vendor js script `feedback-widget.js` that couldn't seem to load properly. Did we have this issue before the widget was commented out?

2023-04-28 20:36 UTC, mDuo13 requested changes

2023-04-28 20:36 UTC, mDuo13 commented on template/component-feedback-widget.html.jinja
> +<script src="../../assets/vendor/feedback-widget.js"></script>
This change (replacing `{{currentpage.prefix}}` with `../../`) is why the feedback widget script is not loading as expected. If you revert this part, it should be fine.

2023-05-15 19:37 UTC, pdp2121 commented
@mDuo13 the preview is ready for reviews. You can check this link:
https://xrplf.github.io/xrpl-dev-portal/pr-preview/feedback-widget/xrpl-quickstart.html

2023-05-16 22:20 UTC, mDuo13 commented
The thumbs-up/down icons aren't showing up in the preview, but they should work in prod (absolute URLs will only work in prod, relative URLs would work in both prod and staging—I think these URLs are coming from the JS for the feedback widget somehow). So could be improved but it's OK as-is.

Placement of the popup on mobile is a bit off, and in general having it as a popup is kind of annoying as it obstructs important parts of the page before you've even had a chance to read them and decide if the page was helpful.

I seem to recall that at some point we had the widget "docked" to below the main article in the center column so it wasn't a popup at all, but something seems to have changed to make that not apply any more. One way to do that again is to add these rules to the CSS:

```css
#feedback-content .docked-widget {
    position: static !important;
    box-shadow: none !important;
    width: auto !important;
}
```

Also, in light mode, the "How can we do better?" text area has white text on a white background. You can fix that with:

```scss
html.light #feedback-content .widget-form-wrapper textarea {
    color: $black;
}
```

I think with those adjustments, this should be almost good to go—one other thing to look out for is conflicts / versioning of the CSS file. [This comment](https://github.com/XRPLF/xrpl-dev-portal/pull/1866#discussion_r1191611959) explains general steps for incrementing the CSS file, but because both this PR and #1866 need to modify the CSS file, one of them needs to rebase onto the other and rebuild with the SCSS edits from both. (If we deploy the edits together, then only one version increment is needed; otherwise, we need to increment twice.)

2023-05-17 19:06 UTC, pdp2121 commented
@mDuo13 Thanks for your feedbacks! I'm not sure why my changes in this commit to make the widget "docked" below center section was not reflected on the preview (rules did not show up on Inspect as well):
https://github.com/XRPLF/xrpl-dev-portal/pull/1892/commits/937e4caf35a94181b5ab6faef6c2431e601cfe4e
even though it worked locally.

Also, the "How can we do better?" text area is black in the preview on my end, with the following code:
`.widget-form-wrapper {
    textarea {
      background-color: $gray-100 !important;
    }

    .widget-header-title {
      color: $gray-900 !important;
    }
}`
in `_light-theme.scss`

I will coordinate with Caleb and Jackson on CSS file versioning.

2023-05-17 19:45 UTC, pdp2121 commented
Preview was fixed. widget should be docked now.

2023-05-18 18:13 UTC, ckniffen commented
The text color is white so I cant see what I typed out.  The dots are spellcheck.
![Monosnap Tokens - XRPL org 2023-05-18 13-12-51](https://github.com/XRPLF/xrpl-dev-portal/assets/464895/db182ea6-5c7b-4878-b08a-c59914689ea0)

2023-05-18 22:11 UTC, pdp2121 commented
> The text color is white so I cant see what I typed out. The dots are spellcheck. ![Monosnap Tokens - XRPL org 2023-05-18 13-12-51](https://user-images.githubusercontent.com/464895/239345595-db182ea6-5c7b-4878-b08a-c59914689ea0.png)

@ckniffen Can you try again? It worked for me as I tested just now in preview. It could be preview issue.

![Screenshot 2023-05-18 at 6 09 24 PM](https://github.com/XRPLF/xrpl-dev-portal/assets/71317875/e00fbec8-bcab-4296-8c13-8de9b73e1dff)

2023-05-18 23:02 UTC, pdp2121 commented
@mDuo13 I think you are right. Caleb and I just figured that the color of the textarea changes based on OS theme color so we should have a fixed color for it. I will make the change you (and Caleb) suggested now.

2023-05-22 20:33 UTC, ckniffen commented on styles/light/_light-theme.scss
> +  // .docked-widget {
delete commented out code.

2023-05-22 20:33 UTC, ckniffen approved these changes

2023-05-25 18:38 UTC, intelliot commented
Where does the feedback go, and who will review it?

2023-06-02 20:04 UTC, pdp2121 commented
> Where does the feedback go, and who will review it?

@intelliot It will be sent to Google Analytics (I'm not sure who's going to review though). The previous portal that we used for feedbacks is deprecating next month. There's has been a GA4 version set up for xrpl.org, and we will need to add mappings for feedbacks. I'm reaching out to people to handle this.

2023-06-06 19:49 UTC, mDuo13 commented
The preview looks good, but can you rebase on the latest master and rebuild the CSS to resolve merge conflicts?

2023-06-06 19:49 UTC, mDuo13 approved these changes

2023-06-26 16:57 UTC, pdp2121 commented
This can be merged now as we have successfully created data layer push event for gtm, as discussed with Caleb and Atilla.

2023-06-26 17:44 UTC, merged