New iconset
XRPLF/xrpl-dev-portal pull request #1925
Opened 2023-06-01 16:36 UTC by AKCodez

2023-07-06 20:33 UTC, mDuo13 approved these changes

2023-07-06 20:38 UTC, mDuo13 requested changes
When I build this locally, it looks like the changes to the up-right arrow cause it to clip out of the line for the external links in the docs sidebar. Take a look at `client-libraries.html` for some examples. The preview on github.io looks different, but I think that's probably a glitch of the staging build.

2023-07-06 22:00 UTC, AKCodez commented
> When I build this locally, it looks like the changes to the up-right arrow cause it to clip out of the line for the external links in the docs sidebar. Take a look at `client-libraries.html` for some examples. The preview on github.io looks different, but I think that's probably a glitch of the staging build.

I am experiencing the same issue, locally it is being displayed as expected but on the preview link it is showing the incorrect code, as for the the up right arrow clipping out of the line - I can not recreate this locally.

2023-07-12 21:31 UTC, mDuo13 approved these changes
Updates look good

2023-07-12 21:32 UTC, merged