Information Architecture updates (again)
XRPLF/xrpl-dev-portal pull request #1934
Opened 2023-06-05 23:29 UTC by mDuo13

This continues the work from the IA.v2 branch but addresses issues that came up in reconciling changes with the master branch

2023-06-08 00:17 UTC, mDuo13 commented
Rebased and force-pushed to fix the merge commit. Hopefully this will be the last.

2023-07-28 02:45 UTC, develoQ commented
The following file isn't used anywhere in `dactyl-config.yml
content/concepts/introduction/xrp.md

2023-08-14 17:17 UTC, Silkjaer requested changes
Thanks for this great update, it's overall a fantastic rearrangement and additions to the already good documentation. I added a few notes, and have shared preview links with a few others to get some external feedback that i'll be adding in a few days (if any).

2023-08-14 17:17 UTC, Silkjaer commented on content/concepts/introduction/what-is-xrp.md
> +At the time of its creation, there were 100 billion XRP. XRP are held in escrow and sold at intervals that help to maintain the stability of the currency and ensure that the general supply grows pred
This should be elaborated. XRP is held in escrow, but released to whom and is the sales only to help maintain the stability of the currency?

2023-08-14 17:17 UTC, Silkjaer commented on content/concepts/introduction/what-is-xrp.md
> +### Naming
Should add a paragraph about trademarks.

2023-08-21 07:03 UTC, develoQ requested changes

2023-08-21 07:03 UTC, develoQ commented on content/contributing/documentation-languages.md
> +If you want to translate the XRP Ledger Dev Portal into your native language of choice, start with the [XRP Ledger Overview file](https://github.com/XRPLF/xrpl-dev-portal/blob/master/content/concepts
When this PR is merged into the master branch, `content/concepts/introduction/xrp-ledger-overview.md` will not exist.

2023-08-31 23:04 UTC, mDuo13 commented
@develoQ I believe the changes you requested have been addressed by #2091.
@Silkjaer I believe the changes you requested have been addressed by #2099.

2023-09-01 04:31 UTC, develoQ requested changes
<img width="729" alt="スクリーンショット 2023-09-01 13 28 30" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/8e0d3121-840d-49ec-aa1c-312fed0a81bc">

Error logs are being output at build time that were not there before.

 I will now check other Japanese-related sections, including #2091.

2023-09-01 06:51 UTC, Silkjaer approved these changes
LGTM content-wise and ready to merge if the issues @develoQ mentioned are fixed.

2023-09-01 06:58 UTC, develoQ approved these changes
There were no serious problems with the Japanese pages.

I have made some fixes to improve side-nav,top-nav for japanese.

If this PR will be merged into the main branch soon, I'll create a PR for main branch after the merge.
If it will not be merged for a while, I will create a PR targeting IA.v3 branch.

2023-09-01 13:23 UTC, amarantha-k commented
Yes, we plan to merge soon. 
+1 to creating a PR for the main branch after the merge. 
Thanks for your contribution!

2023-09-01 19:40 UTC, merged