Add conditional escrows, rename time escrows
XRPLF/xrpl-dev-portal pull request #1953
Opened 2023-06-13 20:55 UTC by DennisDawson

2023-07-24 21:51 UTC, mDuo13 requested changes

2023-07-24 21:51 UTC, mDuo13 commented on content/_code-samples/quickstart/js/ripplex1-send-xrp.js
Should we drop "ripplex" from these filenames?

2023-07-24 21:51 UTC, mDuo13 commented on content/_code-samples/quickstart/js/quickstart.zip
There are still several places linking to the `quickstart.zip` file (they link to the file as stored in the master branch). Those will eventually become broken links when this is merged to master, although the link checker isn't catching them now because they aren't broken yet. Still, we should probably fix those at the same time as removing the zip.

I did a quick search and turned up 25 results in 15 files on IA.v3 that link to `quickstart.zip`. I'd recommend updating those at the same time as removing the file, maybe in a separate PR from this one with the escrow tutorials.

2023-09-06 19:06 UTC, closed without merging

2023-09-06 19:07 UTC, DennisDawson commented
Fixing these issues in new PRs post-IA.v3.