rippled 1.11.0 changes
XRPLF/xrpl-dev-portal pull request #1976
Opened 2023-06-24 01:02 UTC by mDuo13

- [x] Fix #1970 
- [x] Document https://github.com/XRPLF/rippled/pull/4404
- [x] Document https://github.com/XRPLF/rippled/pull/4459
- [ ] Document https://github.com/XRPLF/rippled/pull/4352
- [ ] Document https://github.com/XRPLF/rippled/pull/4291
- [ ] Document https://github.com/XRPLF/rippled/pull/4406 (the amendment has already been added to the Known Amendments page, but the new field `FirstNFTSequence` needs to be added to the AccountRoot reference)

2023-06-24 03:15 UTC, develoQ commented
Is it possible to change the Japanese content (*.ja.md) as well, so that it can remain in English?

I think it's better to have the information that new parts are untranslated than to have the content remain old and not updated.

2023-06-27 01:02 UTC, mDuo13 commented
> Is it possible to change the Japanese content (*.ja.md) as well, so that it can remain in English?
> 
> I think it's better to have the information that new parts are untranslated than to have the content remain old and not updated.

I agree that it's better, but it's a lot more work to find the appropriate places to update the Japanese docs every time we make a change. I would rather just mark the pages as needing translation updates and prioritize them.

2023-06-27 17:01 UTC, ximinez requested changes

2023-06-27 17:01 UTC, ximinez commented on content/references/http-websocket-apis/public-api-methods/account-methods/account_info.md
> +| `disallowIncomingTrustline` | Boolean | If `true`, the account does not allow others to make [trust lines](trust-lines-and-issuing.html) to it. |
AFAIK, these fields are not returned unless the `featureDisallowIncoming` amendment is enabled.

2023-06-27 17:05 UTC, DennisDawson approved these changes
Looks good. Some ignorable suggestions just to prove I read the whole thing.

2023-06-27 17:05 UTC, DennisDawson commented on content/references/http-websocket-apis/admin-api-methods/status-and-debugging-methods/feature.md
> +| `vetoed`    | Boolean or String | For most amendments, this is a boolean value indicating whether the server has been instructed to vote against this amendment. For amendments that are marked as ob
This is subjective and nit-picky, but I would italicize _obsolete_ since we're talking about a word as a word. "For amendments that are marked as _obsolete_ in the code...."

2023-06-27 17:05 UTC, DennisDawson commented on content/references/http-websocket-apis/public-api-methods/account-methods/account_info.md
> +The following fields are deprecated and should not be provided: `ident`, `ledger`, `strict`.
I always cringe at _should_, because it suggests there are times you would use them. Perhaps "The following fields are deprecated." or "The following fields are deprecated and ignored."

2023-06-27 17:05 UTC, DennisDawson commented on content/references/protocol-reference/transactions/transaction-common-fields.md
> +The `NetworkID` field is a protection against "cross-chain" transaction replay attacks, preventing the same transaction from being copied over and executing on a [parallel network](parallel-networks.
If this is important enough for bold and all caps, does it warrant a call out as a warning?

2023-06-27 20:20 UTC, mDuo13 commented on content/references/http-websocket-apis/public-api-methods/account-methods/account_info.md
> +The following fields are deprecated and should not be provided: `ident`, `ledger`, `strict`.
I think `ident` is ignored, `ledger` will technically still work but it's more ambiguous than using one of `ledger_index`/`ledger_hash`, and passing in a non-default (`true`) value for `strict` works but is now the same as the default. (Previously the default, strict=false, meant that you could provide a secret key or something in the account field, which is a bad idea shortcut that was used by automated tests once upon a time.)

So, while there's no reason when you _should_ use them, a case where you _would_ use `strict=true` is if you were writing code that's backwards compatible with older rippled versions (including forked/branched code running on some test networks/sidechains) but still secure.

2023-06-30 03:27 UTC, intelliot approved these changes
Awesome - great updates!

2023-07-05 21:35 UTC, merged