Update ter-codes.md
XRPLF/xrpl-dev-portal pull request #2006
Opened 2023-07-18 05:15 UTC by intelliot

Current description is misleading given the actual meaning of most `ter` codes.

Context: https://github.com/XRPLF/rippled/pull/4504

If and when `terSUBMITTED` is added to `rippled`, a badge indicating the relevant version could be added: e.g. `[New in: rippled 1.12.0][]` (if it is added in 1.12.0).

2023-07-18 10:18 UTC, justinr1234 approved these changes

2023-07-19 00:55 UTC, mtrippled commented
@intelliot Should these descriptions mirror those in https://github.com/XRPLF/rippled/blob/develop/src/ripple/protocol/TER.h#L41-L248 ?

2023-07-19 16:59 UTC, intelliot commented
> @intelliot Should these descriptions mirror those in https://github.com/XRPLF/rippled/blob/develop/src/ripple/protocol/TER.h#L41-L248 ?

Sure, why not?

2023-07-19 17:01 UTC, mtrippled commented
> > @intelliot Should these descriptions mirror those in https://github.com/XRPLF/rippled/blob/develop/src/ripple/protocol/TER.h#L41-L248 ?
> 
> Sure, why not?

I went ahead and updated the ter* comments in rippled source accordingly on the "periodic" PR: https://github.com/XRPLF/rippled/pull/4505

2023-07-24 17:20 UTC, mDuo13 requested changes
Generally good improvements although I have one requirement to maintain

2023-07-24 17:20 UTC, mDuo13 commented on content/references/protocol-reference/transactions/transaction-results/ter-codes.md
> +| `terSUBMITTED`   | Transaction has been submitted, but not yet applied.      |
The codes were in alphabetical order before. I'd like to keep that, just so it's easier to find the result code you're looking for.

2023-07-31 21:38 UTC, intelliot commented on content/references/protocol-reference/transactions/transaction-results/ter-codes.md
> +| `terSUBMITTED`   | Transaction has been submitted, but not yet applied.      |
In that case, I think `terRETRY` was in the wrong row. Anyway, fixed by 4dd8918

2023-07-31 21:39 UTC, intelliot commented on content/references/protocol-reference/transactions/transaction-results/ter-codes.md
> +| `terSUBMITTED`   | Transaction has been submitted, but not yet applied.      |
Fixed

2023-08-02 21:36 UTC, mDuo13 approved these changes

2023-08-02 21:36 UTC, merged