change limit description for all API's required
XRPLF/xrpl-dev-portal pull request #2008
Opened 2023-07-18 20:17 UTC by PeterChen13579

The description of "limit" field will need to be changed for many of the API's to help clarify that values below 10 will be set to 10 and values above 400 will be set to 400. More information can be found here: https://github.com/XRPLF/xrpl-dev-portal/issues/1985 

I will change the rest of the api's that has the "limit" field to the new description once approved/changed.

2023-07-18 20:20 UTC, PeterChen13579 commented
@mDuo13 Please review this change. Thanks! 😄

2023-07-18 21:26 UTC, mDuo13 requested changes

2023-07-18 21:26 UTC, mDuo13 commented on content/references/http-websocket-apis/public-api-methods/account-methods/account_channels.md
> +| `limit`               | Number               | No        | Set transaction retrieval limit between 10 and 400. Invalid numbers are replaced with the closest valid option. Default is 200.|
Please keep the language closer to the original where possible.

```suggestion
| `limit`               | Number               | No        | Limit the number of transactions to retrieve. Cannot be less than 10 or more than 400. Values outside this range are replaced with the closest valid option. The default is 200. |
```

2023-08-02 21:41 UTC, mDuo13 approved these changes

2023-08-02 21:41 UTC, merged