Add Api Version differences
XRPLF/xrpl-dev-portal pull request #2023
Opened 2023-07-27 19:20 UTC by PeterChen13579

Documenting issue [4545](https://github.com/XRPLF/rippled/issues/4545)

2023-07-27 19:27 UTC, PeterChen13579 commented
Hi @mDuo13! There was a bunch of PR's that got merged ([here](https://github.com/XRPLF/rippled/issues/4303), [here](https://github.com/XRPLF/rippled/issues/4539) and [here](https://github.com/XRPLF/rippled/issues/4288) regarding bugs/discrepancies for certain user input calls. In general, all the fix(new behavior) is set for api_version 2, while the old behavior is set for api_version 1. I was wondering how we should document this in the docs? Take a look at my changes as an example. (doubt it will actually be like this though) Thanks for the help 😄

2023-07-31 21:53 UTC, intelliot commented
For simplicity, I suggest just documenting the latest version (and putting `"api_version": 2` in the request). Of course, this should only be merged/deployed after the new version has been widely deployed in production. There should also an "added in" badge to show which version of `rippled` is being documented.

There can be a small note to indicate that older API versions exist, perhaps with a link to https://github.com/XRPLF/rippled/blob/develop/API-CHANGELOG.md for those who want to read about those historical versions.

2023-08-09 20:40 UTC, intelliot commented
"here" is not good [anchor text](https://moz.com/learn/seo/anchor-text). @thejohnfreeman or @mDuo13 , could you perhaps explain why, and offer an alternative?

2023-08-09 22:19 UTC, thejohnfreeman requested changes
Links to "here" hide the destination and are hostile to screen readers. Prefer [linking](https://www.smashingmagazine.com/2012/06/links-should-never-say-click-here/) to nouns at the end of a sentence.

2023-08-09 22:19 UTC, thejohnfreeman commented on content/references/http-websocket-apis/public-api-methods/account-methods/account_info.md
> +Older Api versions can be used. Documented [here][api-version-history]
```suggestion
Older [API versions][api-version-history] can be used.
```

2023-08-09 22:19 UTC, thejohnfreeman commented on content/references/http-websocket-apis/public-api-methods/account-methods/account_tx.md
> +Older Api versions can be used. Documented [here][api-version-history]
```suggestion
Older [API versions][api-version-history] can be used.
```

2023-08-09 22:19 UTC, thejohnfreeman commented on content/references/http-websocket-apis/public-api-methods/ledger-methods/ledger_entry.md
> +Older Api versions can be used. Documented [here][api-version-history]
```suggestion
Older [API versions][api-version-history] can be used.
```

2023-08-10 15:09 UTC, PeterChen13579 commented
@intelliot @thejohnfreeman Thank you for the feedback, that makes complete sense! 😄 I changed it to what @thejohnfreeman suggested~

2023-08-10 16:33 UTC, thejohnfreeman commented
I think this will need a style review from one of our writers. My thoughts and opinions:

- "API" needs to be fully capitalized everywhere it is used. Never "Api".
- There should not be a section named "API Version 2". We should not be adding new sections for every API version. I anticipate, especially now that the gates are open, that we will be adding many versions. Alternatively, we can have a `CHANGELOG` section that lists the changes in each API version, or we can add notes to existing sections, e.g. "Possible Errors", tagged with "New in version 2" or "Added in version 2" or "Changed in version 2" or similar.
- We already have a section on xrpl.org explaining [API Versioning](https://xrpl.org/request-formatting.html#api-versioning), and we already document [how to choose the API version in a request](https://xrpl.org/request-formatting.html#websocket-format). We should link the CHANGELOG on GitHub from that page, and we should link the API Versioning section from every "Added in version X" note in the rest of the documentation.

2023-08-15 18:49 UTC, PeterChen13579 commented
Hi, just a heads up, my internship with Ripple will be ending next Friday. I don't know if there will be a style guideline by then for API version 2, so perhaps @mDuo13 can take over or assign my few changes to someone else. Thanks

2023-09-07 11:26 UTC, mDuo13 commented
I plan to take a different approach to document API v2 differences before it becomes enabled (currently expected in server version 1.13.0)

2023-09-07 11:26 UTC, closed without merging