known amendments - add PayChan, SHAMapV2, uncomment OwnerPaysFee
XRPLF/xrpl-dev-portal pull request #211
Opened 2016-09-13 21:11 UTC by mDuo13

Adds 3 more amendments that we expect to be in rippled 0.33.0.

- In the "Known Amendments" table, the "Introduced" field is left as TBD in case testing finds a problem that causes us to omit the amendment from 0.33.0
- Amendments in the Known Amendments table are sorted with the newest Amendments at the top. (First by when they were enabled, then by when they were introduced.) Currently we don't have concrete plans for when we'll be voting in favor of each amendment, but I think Flow comes first? We might also enable PayChan on the altnet for testing.

2016-09-13 21:35 UTC, ryangyoung commented on content/concept-amendments.md
> +Fixes an inconsistency in the way [transfer fees](concept-transfer-fees.html) are calculated between [OfferCreate](reference-transaction-format.html#offercreate) and [Payment](reference-transaction-f
> Without this amendment, the initial sender of a transaction pays the transfer fees for offers that are executed as part of payment processing, but the holder of the issuances pays the transfer fee if an offer is executed in offer placement. With OwnerPaysFee, the holder of the issuances always pays the transfer fee, regardless of whether the offer is executed as part of a Payment or an OfferCreate transaction. Offer processing outside of payments is unaffected.

To make this a little easier to follow, maybe make these sentences more parallel. E.g. "Without OwnerPaysFee, the holder of the issuance..."

2016-09-13 21:42 UTC, ryangyoung commented on content/concept-amendments.md
> +Creates "Payment Channels" for XRP. Payment channels are a tool for facilitating repeated unidirectional payments or extensions of credit between two parties, which we expect to be used with the Inte
> which we expect to be used with the Interledger Protocol.

Who is "we" there? That should be Ripple.

2016-09-13 21:43 UTC, ryangyoung commented on content/concept-amendments.md
> +Creates three new transaction types: `ChannelCreate`, `ChannelFund`, and `ChannelClaim`. Creates a new ledger node type, `Channel`. Defines an off-ledger data structure called a `Claim`, used in the
Add links to the appropriate sections of the docs, once those docs exist.

2016-09-13 23:35 UTC, nbougalis commented on content/concept-amendments.md
> +Creates "Payment Channels" for XRP. Payment channels are a tool for facilitating repeated unidirectional payments or extensions of credit between two parties, which we expect to be used with the Inte
Hyperlink "Interledger Protocol" maybe?

2016-09-13 23:36 UTC, nbougalis commented on content/concept-amendments.md
> +Creates "Payment Channels" for XRP. Payment channels are a tool for facilitating repeated unidirectional payments or extensions of credit between two parties, which we expect to be used with the Inte
"To be used" -> "will be used" maybe?

2016-09-13 23:37 UTC, nbougalis commented on content/concept-amendments.md
> +Changes the hash tree structure that `rippled` uses to represent a ledger. The new structure is smaller and more efficient than the previous version. This affects how ledger hashes are calculated, bu
Perhaps "compact" is a better choice of words than "smaller".

2016-09-13 23:50 UTC, mDuo13 commented on content/concept-amendments.md
> +Creates "Payment Channels" for XRP. Payment channels are a tool for facilitating repeated unidirectional payments or extensions of credit between two parties, which we expect to be used with the Inte
I changed this line to say:
> Ripple expects this feature to be useful for the [Interledger Protocol](https://interledger.org/).

2016-09-14 00:36 UTC, seelabs commented on content/concept-amendments.md
> +Creates "Payment Channels" for XRP. Payment channels are a tool for facilitating repeated unidirectional payments or extensions of credit between two parties. Ripple expects this feature to be useful
What is meant by "or extensions of credit" here? When a sender signs an authorization is that considered "extending credit"? If so, then that's fine.

2016-09-14 00:38 UTC, mDuo13 commented on content/concept-amendments.md
> +Creates "Payment Channels" for XRP. Payment channels are a tool for facilitating repeated unidirectional payments or extensions of credit between two parties. Ripple expects this feature to be useful
Yeah, that's what I meant. But maybe it should be reworded so it can't be confused with RCL trust lines...

2016-09-14 16:16 UTC, HowardHinnant commented
👍

2016-09-15 20:38 UTC, ryangyoung commented on content/concept-amendments.md
> +Fixes an inconsistency in the way [transfer fees](concept-transfer-fees.html) are calculated between [OfferCreate](reference-transaction-format.html#offercreate) and [Payment](reference-transaction-f
Nitpick: change "Without this amendment" in the second sentence to "Without OwnerPaysFee". Or "With OwnerPaysFee" to "With this amendment" to make them parallel. Unless there's a good reason not to that I'm not thinking of.

2016-09-15 20:41 UTC, ryangyoung commented on content/concept-amendments.md
> +Creates "Payment Channels" for XRP. Payment channels are a tool for facilitating repeated, unidirectional payments or temporary credit between two parties. Ripple expects this feature to be useful fo
> Payment channels are a tool for facilitating repeated, unidirectional payments or temporary credit between two parties. 

Should that be: 

> Payment channels are a tool for facilitating repeated, unidirectional payments or *extending* [or similar verb] temporary credit between two parties.

2016-09-15 20:42 UTC, ryangyoung requested changes
Made two small comments that aren't substantive. If I'm wrong on either of them, go ahead and merge.

2016-09-15 20:44 UTC, mDuo13 commented on content/concept-amendments.md
> +Creates "Payment Channels" for XRP. Payment channels are a tool for facilitating repeated, unidirectional payments or temporary credit between two parties. Ripple expects this feature to be useful fo
It's funny, I _just_ changed it _not_ to use the verb "extending" because I didn't want it to sound like "extending a trust line" or something.

2016-09-15 20:44 UTC, mDuo13 commented on content/concept-amendments.md
> +Creates "Payment Channels" for XRP. Payment channels are a tool for facilitating repeated, unidirectional payments or temporary credit between two parties. Ripple expects this feature to be useful fo
I think it's better as-is -- "facilitating... temporary credit"

2016-09-15 20:55 UTC, merged

2016-09-15 20:58 UTC, ryangyoung commented on content/concept-amendments.md
> +Creates "Payment Channels" for XRP. Payment channels are a tool for facilitating repeated, unidirectional payments or temporary credit between two parties. Ripple expects this feature to be useful fo
Fair enough re: the trust line confusion, but the distance between the verb and object makes the sentence a bit harder to parse on first glance.