(Re-)Add Automated Market Maker docs
XRPLF/xrpl-dev-portal pull request #2112
Opened 2023-09-07 11:18 UTC by mDuo13

Restores AMM reference docs that were removed by #1867 and #1874 now that AMM is part of the version 1.12.0 release. The English versions are updated to follow changes from [Ripple Open Source](https://opensource.ripple.com). The Japanese versions are not updated with the latest changes like AMMDelete, error code changes, and replacing the `lsfAMM` flag in AccountRoot with the `AMMID` field.

The "Create an AMM" tutorial should follow shortly in a separate PR.

2023-09-08 19:52 UTC, amarantha-k approved these changes
Ran a spot check on the preview URL and it looks good

2023-09-08 21:28 UTC, merged

2023-09-11 08:54 UTC, gregtatcam requested changes

2023-09-11 08:54 UTC, gregtatcam commented on content/concepts/tokens/automated-market-makers.md
> +Automated Market Makers (AMMs) are smart contracts that provide liquidity in the XRP Ledger's decentralized exchange. Each AMM holds a pool of two assets and enables users to swap between them at an
Why `smart contracts`?

2023-09-11 08:54 UTC, gregtatcam commented on content/concepts/tokens/automated-market-makers.md
> +LP Tokens are like other tokens in the XRP Ledger, so you can use them in many [types of payments](payment-types.html), trade them in the decentralized exchange, or even deposit them as assets for ne
We don't allow AMMCreate with LPTokens.

2023-09-11 08:54 UTC, gregtatcam commented on content/concepts/tokens/automated-market-makers.md
> +Unlike any previous Automated Market Makers, the XRP Ledger's AMM design has an _auction slot_ that a liquidity provider can bid on to get a discount on the trading fee for a 24-hour period. The bid
Discounted fee is tradingFee/10.

2023-09-11 08:54 UTC, gregtatcam commented on content/concepts/tokens/automated-market-makers.md
> +Unlike any previous Automated Market Makers, the XRP Ledger's AMM design has an _auction slot_ that a liquidity provider can bid on to get a discount on the trading fee for a 24-hour period. The bid
LP Tokens left after reimbursing the previous owner are burnt.

2023-09-11 08:54 UTC, gregtatcam commented on content/concepts/tokens/automated-market-makers.md
> +
We added DirectoryNode entry to link AMM AccountRoot and AMM object to enable ledger_entry for amm type.

2023-09-11 08:54 UTC, gregtatcam commented on content/concepts/tokens/automated-market-makers.md
> +An AMM is deleted when an [AMMWithdraw transaction][] withdraws all assets from its pool. This only happens by redeeming all of the AMM's outstanding LP Tokens. Deleting the AMM includes removes all
Typo -`includes removes`?

2023-09-11 08:54 UTC, gregtatcam commented on content/concepts/tokens/automated-market-makers.md
> +
We also delete `DirectoryNode` AMM entry along with `AccountRoot` and `AMM` object.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/http-websocket-apis/public-api-methods/ledger-methods/ledger_entry.md
> +- [`amm`](#get-amm-object) :not_enabled:
It's enabled now.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/ledger-data/ledger-object-types/amm.md
> +    ]
Should add `OwnerNode`.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/ledger-data/ledger-object-types/amm.md
> +
Should add `OwnerNode`.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/transactions/transaction-results/tec-codes.md
> +| `tecAMM_UNFUNDED`        | 162   | The [AMMCreate transaction][] failed because the sender does not have enough of the specified assets to fund it. _(Requires the [AMM amendment][] :not_enabled:)_
changed to `tecUNFUNDED_AMM`

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/transactions/transaction-results/tec-codes.md
> +| `tecAMM_UNFUNDED`        | 162   | The [AMMCreate transaction][] failed because the sender does not have enough of the specified assets to fund it. _(Requires the [AMM amendment][] :not_enabled:)_
Also `AMMDeposit`.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/transactions/transaction-results/tec-codes.md
> +| `tecAMM_BALANCE`         | 163   | The [AMMDeposit][] or [AMMWithdraw][] transaction failed because either the AMM or the user does not hold enough of one of the specified assets. (For example, you
`AMMWithdraw` only.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/transactions/transaction-results/tec-codes.md
> +| `tecAMM_FAILED`          | 164   | The AMM-related transaction failed. For [AMMDeposit][] or [AMMWithdraw][] this could be because the sender does not have enough of the specified assets, or the tr
No longer used in `AMMVote`.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/transactions/transaction-types/ammbid.md
> +You cannot specify both `BidMin` and `BidMax`.
You can.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/transactions/transaction-types/ammbid.md
> +    **Caution:** This minimum value is a placeholder and may change before the AMM feature becomes finalized.
Min slot price is `LPTokensBalance * tradingFee / 25`.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/transactions/transaction-types/ammbid.md
> +| `tecAMM_INVALID_TOKENS` | The sender of this transaction does not hold enough LP Tokens to meet the slot price. |
Or the account is not `LP`.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/transactions/transaction-types/ammcreate.md
> +One or both of `Amount` and `Amount2` can be [tokens](tokens.html); at most one of them can be [XRP](xrp.html). They cannot both have the same currency code and issuer. The tokens' issuers must have
Can't use AMM LP tokens as assets for another AMM.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/transactions/transaction-types/ammdelete.md
> +Normally, an [AMMWithdraw transaction][] automatically deletes an AMM and all associated ledger entries when it withdraws all the assets from the AMM's pool. However, if there are too many trust line
And the `DirectoryNode` entry.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/transactions/transaction-types/ammdeposit.md
> +
`TradingFee` if `tfTwoAssetIfEmpty` is set.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/transactions/transaction-types/ammdeposit.md
> +This transaction has five modes, defined by which flag you specify. Each mode expects a specific combination of fields. The modes fall into two categories:
Six modes.

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/transactions/transaction-types/ammdeposit.md
> + The formula for how many LP Tokens you receive for a double-asset deposit is:
Shouldn't this be `single-asset`?

2023-09-11 08:54 UTC, gregtatcam commented on content/references/protocol-reference/transactions/transaction-types/ammdeposit.md
> +{{ include_svg("img/amm-single-asset-deposit-formula.svg", "L = T × ( (( 1 + (B - (F × (1 - W) × B)) ÷ P)^W) - 1)") }}
The formula changed per Certik review request and is a lot more complicated.