rippled 0.33 - load_factor changes
XRPLF/xrpl-dev-portal pull request #220
Opened 2016-10-19 00:17 UTC by mDuo13

2016-10-20 17:19 UTC, ryangyoung commented
LGTM 👍

2016-10-21 20:14 UTC, ximinez requested changes
Generally looks good. I'm unsure about the need for change notation...

2016-10-21 20:14 UTC, ximinez commented on content/reference-rippled.md
> +| `load_factor`                       | Number                    | The load factor the server is currently enforcing, as a multiplier on the base transaction cost. For example, at `1000` load factor
Should this include `[Updated in: rippled 0.33.0][]`?

2016-10-21 20:14 UTC, ximinez commented on content/reference-rippled.md
> +| `load_factor`                    | Number           | The load factor the server is currently enforcing. The ratio between this value and the `load_base` determines the multiplier for transaction c
Should this include `[Updated in: rippled 0.33.0][]`?

2016-10-21 20:23 UTC, ximinez commented on content/reference-rippled.md
> +| `load_factor`                       | Number                    | The load factor the server is currently enforcing, as a multiplier on the base transaction cost. For example, at `1000` load factor
On further thought, would it be worth including that this is the "load-scaled open ledger transaction cost" or something like that?  `load_factor_server` could then note that factor is sufficient to get into the transaction queue.  The link to "open ledger cost" is probably sufficient, but I'm not sure.

2016-10-24 23:13 UTC, merged