ecosystem updates mismatching modals vs cards
XRPLF/xrpl-dev-portal pull request #2247
Opened 2023-11-01 19:00 UTC by AKCodez

2023-11-15 22:22 UTC, mDuo13 requested changes
Generally looks good, but let's not add more title case image files.

2023-11-15 22:22 UTC, mDuo13 commented on assets/img/uses/modalLogos/Cryptum.png
Change filename to all lowercase so we don't have to worry about case mismatches on *nix. (Update the CSS accordingly)

2023-11-17 20:30 UTC, AKCodez commented on assets/img/uses/modalLogos/Cryptum.png
done

2023-11-17 20:46 UTC, mDuo13 approved these changes

2023-11-17 20:47 UTC, mDuo13 requested changes

2023-11-17 20:47 UTC, mDuo13 commented on assets/img/uses/modalLogos/Cryptum.png
Actually, it looks like this is not done? Still showing as `Cryptum.png` in the GitHub preview.

2023-11-20 23:43 UTC, mDuo13 commented on assets/img/uses/modalLogos/Cryptum.png
This must be some kind of platform issue, because it's still showing in title case here.

I'll try merging and fixing the problem myself, since I'm on Linux and have a case-sensitive filesystem.

2023-11-21 00:27 UTC, merged