Migrate the toml checker to Redocly (https://xrpl.org/xrp-ledger-toml-checker.html)
XRPLF/xrpl-dev-portal pull request #2274
Opened 2023-11-22 00:48 UTC by JST5000

This migrates this page: https://xrpl.org/xrp-ledger-toml-checker.html

It primarily involves migrating:
1. `xrpl-toml-checker.page.tsx`
2. `xrp-ledger-toml-checker.js`
3. (And moving over the test file `xrp-ledger-toml-checker-test.js`)

2023-12-19 01:00 UTC, mDuo13 requested changes
1. To match the location of the other tools, please put it under `resources/dev-tools/`.
2. Modify the `content/sidebars.yaml` file to add the `page: path/to/file.page.tsx` line. You can skip the `href` line which doesn't actually do anything in my experience.
3. I think there's some kind of error handling problem going on. Testing it on `mduo13.com` on leads to a blank result (with errors in the console). The tool should display the results _especially_ if parsing the TOML or looking up the accounts didn't go well, since the point of this tool is to detect and point out problems.

2023-12-19 01:00 UTC, mDuo13 commented on content/dev-tools/toml-checker/ListTomlFields.tsx
> +// to be a subset of ASCII anyway.
This comment is the continuation of the ones on lines 4-5. It probably shouldn't have a bunch of imports in between.

2023-12-19 01:00 UTC, mDuo13 commented on content/dev-tools/xrpl-toml-checker.page.tsx
Rename to `xrp-ledger-toml-checker.page.tsx` for consistency with the old URL and the name of the file it's checking, and move under `resources/dev-tools/`

2024-01-03 21:55 UTC, JST5000 commented
> * To match the location of the other tools, please put it under `resources/dev-tools/`.
> * Modify the `content/sidebars.yaml` file to add the `page: path/to/file.page.tsx` line. You can skip the `href` line which doesn't actually do anything in my experience.
> * I think there's some kind of error handling problem going on. Testing it on `mduo13.com` on leads to a blank result (with errors in the console). The tool should display the results _especially_ if parsing the TOML or looking up the accounts didn't go well, since the point of this tool is to detect and point out problems.

1st two are done, 3rd one I could not reproduce unfortunately.

2024-01-03 22:17 UTC, merged

2024-01-03 22:17 UTC, mDuo13 commented
Approved and merged with the same sidebar-related changes as #2270.