DEX Integration
XRPLF/xrpl-dev-portal pull request #2433
Opened 2024-03-01 17:37 UTC by oeggert

Updated #2401 for redocly migration.

2024-03-12 22:16 UTC, amarantha-k requested changes
In addition to the inline comments/suggestions, all links need to be updated.

2024-03-12 22:16 UTC, amarantha-k commented on docs/use-cases/defi/integrate-with-xrpl-dex.md
> +For lighter use cases, you can often rely on free public servers. However, more serious use of the XRP Ledger requires your own infrastructure.
Suggest rewording "lighter use cases" and "more serious use" to something like "less complex applications/simpler scenarios" and "more substantial applications/critical use cases"

2024-03-12 22:16 UTC, amarantha-k commented on docs/use-cases/defi/integrate-with-xrpl-dex.md
> +For lighter use cases, you can often rely on free public servers. However, more serious use of the XRP Ledger requires your own infrastructure.
```suggestion
For lighter use cases, you can often rely on free public servers. However, for more substantial application/critical use cases, it is highly recommended to use your own infrastructure.
```

2024-03-12 22:16 UTC, amarantha-k commented on docs/use-cases/defi/integrate-with-xrpl-dex.md
> +XRP is held in _accounts_ (also referred to as _wallets_ or _addresses_  ) on the XRP Ledger. Accounts on the XRP Ledger are different than accounts on other blockchain ledgers, such as Bitcoin, wher
```suggestion
XRP is held in _accounts_ (also referred to as _wallets_ or _addresses_  ) on the XRP Ledger. Accounts on the XRP Ledger are different than accounts on other blockchain ledgers, such as Bitcoin, where accounts incur little to no overhead. In the XRP Ledger, account state is stored per ledger and accounts are [not easy to delete](deleting-accounts.html). To offset the costs associated with storing accounts, each account must hold a separate [reserve of XRP](reserves.html) that can't be sent to others. For these reasons, it is recommended that institutions not create excessive or needless accounts. <!-- STYLE_OVERRIDE: hot wallet, warm wallet, cold wallet, wallet, easy -->
```

2024-03-12 22:16 UTC, amarantha-k commented on docs/use-cases/defi/integrate-with-xrpl-dex.md
> +To follow Ripple's recommended best practices, you should create at least two new accounts on the XRP Ledger. To minimize the risks associated with a compromised secret key, Ripple recommends creatin
```suggestion
To follow the recommended best practices, you should create at least two new accounts on the XRP Ledger. To minimize the risks associated with a compromised secret key, create [_cold_, _hot_, and _warm_ accounts](account-types.html) (these are sometimes referred to, respectively, as cold, hot, and warm wallets). The hot/warm/cold model is intended to balance security and convenience. Exchanges listing XRP should create the following accounts:
```

2024-03-12 22:16 UTC, amarantha-k commented on docs/use-cases/defi/integrate-with-xrpl-dex.md
> +To follow Ripple's recommended best practices, you should create at least two new accounts on the XRP Ledger. To minimize the risks associated with a compromised secret key, Ripple recommends creatin
The link to account-types needs to be updated.

2024-03-12 22:16 UTC, amarantha-k commented on docs/use-cases/defi/integrate-with-xrpl-dex.md
> +XRP are represented on the XRP Ledger as an unsigned integer count of _drops_, where one XRP is 1,000,000 drops. Ripple recommends that your accounting software handles XRP balances in _drops_, but d
```suggestion
XRP are represented on the XRP Ledger as an unsigned integer count of _drops_, where one XRP is 1,000,000 drops. It is recommended that your accounting software handles XRP balances in _drops_, but displays to users their balance in units of XRP.
```

2024-03-12 22:16 UTC, amarantha-k commented on docs/use-cases/defi/integrate-with-xrpl-dex.md
> +To creat ean offer, send an `OfferCreate` transaction.
```suggestion
To create an offer, send an `OfferCreate` transaction.
```

2024-03-18 23:15 UTC, mDuo13 reviewed
Agreed with Amarantha's notes and added a few other comments.

2024-03-18 23:15 UTC, mDuo13 commented on docs/use-cases/defi/integrate-with-xrpl-dex.md
> +- [`Clio`](https://github.com/XRPLF/clio): An API server optimized for RPC calls on the validated historical ledger.
I think this section is missing a key piece of context, which is that Clio _needs_ you to run at least one `rippled` server to pull data from (you can't pull from public servers). So really, the approach businesses should take is to set up a `rippled` server first, then consider adding Clio servers if they need to scale up.

2024-03-18 23:15 UTC, mDuo13 commented on docs/use-cases/defi/integrate-with-xrpl-dex.md
> +To follow Ripple's recommended best practices, you should create at least two new accounts on the XRP Ledger. To minimize the risks associated with a compromised secret key, Ripple recommends creatin
I think the first two sentences of this paragraph feel kind of redundant. Maybe something like this as an intro:

> When integrating with the XRP Ledger, the best practice is to maintain separate _cold_, _hot_, and _warm_ accounts to minimize the risks of secret keys being compromised.

Additionally, it feels redundant to introduce "cold/hot/warm accounts" and then have a parenthetical saying they're also called "cold/hot/warm wallets"—maybe just say these accounts are also called wallets without repeating the cold/hot/warm nomenclature. (I think it got this way because a previous revision used the terms "issuing/operational/standby address" instead.)

2024-03-18 23:15 UTC, mDuo13 commented on docs/use-cases/defi/integrate-with-xrpl-dex.md
> +There isn't a dedicated "create account" transaction. The [Payment](payment.html) transaction automatically creates a new account if the payment sends enough XRP to a mathematically-valid address tha
Maybe this could be simplified by saying:

> To create a new account in the XRP Ledger, you use a Payment transaction to deliver enough XRP to a mathematically-valid address that doesn't already have an account. This is called funding an account, and creates an `AccountRoot` entry in the ledger. The minimum amount of XRP to create a new account is the [account base reserve](#) amount, currently {% $env.PUBLIC_BASE_RESERVE %}. For more information on setting up accounts, see [Creating Accounts](#).

Also, apologies, since I think this paragraph is originally based on some stuff I wrote a long time ago (when the conceptual docs weren't as well fleshed-out, so it felt more important to provide the details here).

2024-03-18 23:15 UTC, mDuo13 commented on docs/use-cases/defi/integrate-with-xrpl-dex.md
> +If you are setting up an exchange to hold custody of user funds, you must manage your own balance sheet to track customers' holdings. In this situation, the exchange's accounts are represented _on-ch
This paragraph is confusing to me. When it says the exchange's accounts are represented _on-chain_ and "can be queried", it almost sounds like people can use the XRPL to look up their balances at the exchange, but I think what it means to say is that anyone can see how much the exchange holds in total _on the XRPL_, but this doesn't tell you:

- which customers those funds are allocated to / in custody for
- what off-XRPL assets the exchange holds

I think it might be good to clarify that since people might get the impression that you _can_ query one or both of those things on the XRPL, especially since this is under the "Managing Off-Ledger Assets" section.

2024-03-18 23:15 UTC, mDuo13 commented on docs/use-cases/defi/integrate-with-xrpl-dex.md
> +# Integrate with the XRPL Decentralized Exchange
I feel this title is a bit too broad. I would love to narrow the focus down to more specific types of business or use case and describe the concerns for each one in more detail, like with the Algorithmic Trading use case.

Or, if the idea behind this doc is to lay down only the basics that are generally the same across use cases, title it accordingly with a word llike "Basics" or "Fundamentals" in the title.

2024-03-18 23:15 UTC, mDuo13 commented on docs/use-cases/defi/integrate-with-xrpl-dex.md
> +**Note:** Any Offer in the DEX that would exchange two tokens can use XRP as an intermediary currency in a synthetic order book. The XRPL DEX automatically uses this bridging technique to improve exc
The callout syntax here should be updated.

```suggestion
{% admonition type="info" name="Note" %}
Any Offer in the DEX that would exchange two tokens can use XRP as an intermediary currency in a synthetic order book. The XRPL DEX automatically uses this bridging technique to improve exchange rates and liquidity when doing so is cheaper than trading token-to-token. To learn more, see: [auto-bridging](autobridging.html).
{% /admonition %}
```

(Note, my suggestion uses the old link, but that should also be updated.)

2024-03-20 10:15 UTC, Jess25051980 approved these changes

2024-03-20 19:54 UTC, oeggert commented
Temporarily closing this PR until we're able to get reviews/comments.

2024-03-20 19:54 UTC, closed without merging