Dev Reflections blog post - VerifyEd
XRPLF/xrpl-dev-portal pull request #2467
Opened 2024-03-15 01:10 UTC by amarantha-k

2024-03-18 15:26 UTC, AKCodez approved these changes

2024-03-18 15:27 UTC, AKCodez requested changes

2024-03-18 15:27 UTC, AKCodez commented on blog/img/dev-reflections-verifyed-logo.png
Need a dark mode version for this icon @amarantha-k

2024-03-18 15:28 UTC, AKCodez commented on blog/img/dev-reflections-verifyed-logo.png
![image](https://github.com/XRPLF/xrpl-dev-portal/assets/43763415/67109d45-2fd8-4a21-a4e0-2910bff075dc)

2024-03-18 15:33 UTC, amarantha-k commented on blog/img/dev-reflections-verifyed-logo.png
I've commented out the logo image for now so we can proceed to publish this blog. Once the dark mode image is available, will update the post.

2024-03-19 16:08 UTC, AKCodez approved these changes

2024-03-19 16:20 UTC, merged