Remove the "not-enabled" flag from AMM topics and update Known Amendments page
XRPLF/xrpl-dev-portal pull request #2487
Opened 2024-03-22 21:01 UTC by amarantha-k

When merged, this PR closes issue #2486

2024-03-22 22:00 UTC, oeggert approved these changes
Approving, but there are a couple not-enabled tags still in the `ledger_data` and `ledger_entry` ledger methods pages.

2024-03-23 00:57 UTC, tequdev commented on resources/known-amendments.md
> +| Default Vote (Latest stable release) | Yes |
Doesn't the Default Vote match rippled’s Feature.cpp?
<img width="888" alt="スクリーンショット 2024-03-23 9 57 21" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/05c6d407-b059-4c4d-8dc7-ec9ff6cabe4e">

2024-03-23 01:47 UTC, mDuo13 requested changes
As tequ noted, the default vote hasn't changed.

2024-03-23 04:15 UTC, amarantha-k commented on resources/known-amendments.md
> +| Default Vote (Latest stable release) | Yes |
Thanks for catching this. Fixed.

2024-03-23 04:24 UTC, tequdev approved these changes
👍

2024-03-23 15:38 UTC, merged