[es-ES] First batch spanish translations
XRPLF/xrpl-dev-portal pull request #2521
Opened 2024-04-02 19:26 UTC by Ekiserrepe

2024-04-04 17:07 UTC, amarantha-k requested changes
Thank you for your contribution - this looks great for the first batch! 
Added suggestions to fix broken links. 
Also, recommend adding a `translations.yaml` file under the @i18n\es-ES\ similar to `https://github.com/XRPLF/xrpl-dev-portal/blob/master/%40i18n/ja/translations.yaml` before merging the first batch for Spanish translations.

2024-04-04 17:07 UTC, amarantha-k commented on @i18n/es-ES/docs/concepts/accounts/account-types.md
> +    - [Cuentas](accounts.md)
```suggestion
    - [Cuentas](index.md)
```

2024-04-04 17:07 UTC, amarantha-k commented on @i18n/es-ES/docs/concepts/accounts/cryptographic-keys.md
> +- En Python 3 en [esta sección de códigos de ejemplo del repositorio]({{target.github_forkurl}}/blob/{{target.github_branch}}/content/_code-samples/key-derivation/py/key_derivation.py).
```suggestion
- En Python 3 en {% repo-link path="_code-samples/key-derivation/py/key_derivation.py" %}esta sección de códigos de ejemplo del repositorio{% /repo-link %}.
```

2024-04-04 17:07 UTC, amarantha-k commented on @i18n/es-ES/docs/concepts/accounts/addresses.md
> +La fórmula para calcular direcciones XRP Ledger desde una clave pública es la siguiente. Para ver el código de ejemplo completo, consulta [`encode_address.js`](https://github.com/XRPLF/xrpl-dev-porta
```suggestion
La fórmula para calcular direcciones XRP Ledger desde una clave pública es la siguiente. Para ver el código de ejemplo completo, consulta [`encode_address.js`](https://github.com/XRPLF/xrpl-dev-portal/blob/master/content/_code-samples/address_encoding/js/encode_address.js). Para el proceso de derivar la clave pública desde una passphrase a un valor semilla, consulta [Derivación de clave](cryptographic-keys.md#key-derivation).
```

2024-04-04 17:07 UTC, amarantha-k commented on @i18n/es-ES/docs/concepts/accounts/deleting-accounts.md
> +Instituciones que reciben y envían valor en nombre de muchos usuarios pueden utilizar [**Source Tags** y **Destination Tags**](source-and-destination-tags.md) para distinguir pagos desde y para sus c
```suggestion
Instituciones que reciben y envían valor en nombre de muchos usuarios pueden utilizar [**Source Tags** y **Destination Tags**](../transactions/source-and-destination-tags.md) para distinguir pagos desde y para sus clientes usando una (o un puñado) de cuentas en el XRP Ledger.
```

2024-04-04 17:44 UTC, Ekiserrepe commented
> Thank you for your contribution - this looks great for the first batch! Added suggestions to fix broken links. Also, recommend adding a `translations.yaml` file under the @i18n\es-ES\ similar to `https://github.com/XRPLF/xrpl-dev-portal/blob/master/%40i18n/ja/translations.yaml` before merging the first batch for Spanish translations.

Thanks for the review, I'll prepare the translations.yaml. Should I close the PR until then?

2024-04-04 23:26 UTC, amarantha-k commented
Thank you! 
You could leave the PR open if you anticipate this work to take a few days to about a week. If you expect it to take longer, then it may be better to close the PR for now.

2024-04-05 20:07 UTC, Ekiserrepe commented
@amarantha-k i think i added the translations.yaml file. Could you check it, please? Thank you!

2024-04-07 16:34 UTC, Ekiserrepe commented
Added @i18n/es-ES/docs/concepts/ledgers folder and files translated.

2024-04-09 22:45 UTC, amarantha-k commented
@Ekiserrepe Thank you! I was able to test locally with the `translations.yaml` file you added.

2024-04-16 17:38 UTC, amarantha-k commented
FYI, waiting on a few localization fixes from Redocly - #2524, #2516

2024-04-21 18:53 UTC, Ekiserrepe commented
Added /networks-and-servers translations

2024-05-15 19:03 UTC, amarantha-k requested changes
Added suggestions to remove the locale information from `redocly.yaml` for now. That way, we can merge the PR to add the translated pages to the master branch. 
As you continue to translate more documentation pages, you can create new PRs that can be reviewed and merged sooner. Once we have a majority of the content translated, we can enable the language dropdown for Spanish on the site by re-adding the locale in the `redocly.yaml` file.

2024-05-15 19:03 UTC, amarantha-k commented on redocly.yaml
> +    - code: es-ES
```suggestion
```

2024-05-15 19:03 UTC, amarantha-k commented on redocly.yaml
> +      name: Español
```suggestion
```

2024-05-17 17:09 UTC, amarantha-k approved these changes
Thanks for incorporating the suggestions. Local build was successful.

2024-05-17 17:20 UTC, merged