Add Partial Payments stand-alone page
XRPLF/xrpl-dev-portal pull request #257
Opened 2017-06-09 01:12 UTC by mDuo13

This page expands on the "Partial Payments" and "delivered_amount" sections of the transaction reference today. It puts special emphasis on avoiding the Partial Payments exploit. I chose not to reference the Gateway Bulletin, which is dated to 2014 and contains several obsolete sections describing Ripple-REST, etc. This document effectively updates that bulletin.

As per usual, the **.md** files are the real changes and the **.html** files are generated from the MD ones, so you don't need to comment on the .html files.

Known omissions from this page (can be fixed in a later version):

- No guidelines on using RippleAPI
- No diagram (I wanted to include a diagram to compare partial and non-partial payments, but couldn't figure out how to structure such a diagram to actually aid understanding here)
- No examples of transaction metadata and how to read it. (Partly this is because transaction metadata is not always shown in the same place for all of the `rippled` APIs, so an explanation would have to get annoyingly specific to describe each case.)

Feel free to object if you think any of those bullet points is a showstopper to prevent this from being published as-is first.

2017-06-09 18:25 UTC, jbheron requested changes
Looks great, nice clear write-up. I'm requesting changes based on what may be some helpful changes, and one item that may be formatted incorrectly.

2017-06-09 18:25 UTC, jbheron commented on content/reference-transaction-format.md
> +A partial payment allows a payment to succeed by reducing the amount received. Partial payments are useful for [returning payments](tutorial-gateway-guide.html#bouncing-payments) without incurring ad
This might be better served as an additional sentence, even with a note or caution flag, as: 

> A partial payment allows a payment to succeed by reducing the amount received. Partial payments are useful for [returning payments](tutorial-gateway-guide.html#bouncing-payments) without incurring additional costs to oneself.

> They can also be used to exploit integrations that naively assume the `Amount` field of a successful transaction always describes the exact amount delivered.


Or:

>  **Note**: They can also be used to exploit integrations that naively assume the `Amount` field of a successful transaction always describes the exact amount delivered.

2017-06-09 18:25 UTC, jbheron commented on content/concept-partial-payments.md
> +When sending a Payment that does not use the Partial Payment flag, the `Amount` field of the transaction specifies the exact amount to deliver, and the `SendMax` field specifies the maximum amount an
> If payment cannot deliver the full `Amount` without exceeding the `SendMax` parameter, or the full amount cannot be delivered for any other reason, the transaction fails.

Needs an article: 

>  If a payment cannot deliver the full `Amount` without exceeding the `SendMax` parameter, or the full amount cannot be delivered for any other reason, the transaction fails.

2017-06-09 18:25 UTC, jbheron commented on content/concept-partial-payments.md
> +[result code]: reference-transaction-format.html#transaction-results
Will this line correctly display the link as formatted?

2017-06-09 18:25 UTC, jbheron commented on content/concept-partial-payments.md
> +For non-partial payments, the `delivered_amount` field of the transaction metadata is equal to the `Amount` field of the transaction. When a payment delivers an issued currency, the `delivered_amount
> ... may be slightly differently than ...

I assume you meant: 

> ... may be slightly different than ...

2017-06-09 18:25 UTC, jbheron commented on content/concept-partial-payments.md
> +7. The malicious actor uses, resells, or absconds with the goods and services before the merchant notices the discrepancy.
Please leave 'absconds with the goods' in this document! <3 :-)

2017-06-09 19:04 UTC, mDuo13 commented on content/concept-partial-payments.md
> +[result code]: reference-transaction-format.html#transaction-results
This reference defines the link used in lines 37 and 38; line 41 does not display in the parsed markdown. Search for _implicit link name_ in [the original Markdown definition](https://daringfireball.net/projects/markdown/syntax)

2017-06-09 20:40 UTC, JoelKatz commented
:+1: LGTM

2017-06-09 21:46 UTC, mDuo13 commented
Still open to more feedback, but we're going to merge this now to get it out there as soon as possible

2017-06-09 21:48 UTC, merged

2017-06-10 19:13 UTC, nbougalis commented on content/concept-partial-payments.md
> +## Partial Payments Exploit
There is no "partial payments exploit" and we shouldn't refer to this as an exploit. This should be named "Implementation Considerations" or "Integrating Support for Partial Payments"

2017-06-10 19:13 UTC, nbougalis commented on content/concept-partial-payments.md
> +To exploit a vulnerable financial institution, a malicious actor does something like this:
I would move the entire section that describes the step-by-step methodology down; it's enough (at this point) to explain that the issue is caused by a recipient examining the `Amount` field instead of the `delivered_amout` field. I would then list the _mitigation_ (the section titled "Avoiding the Exploit", which I would rename to "Properly Handling Partial Payments"). 

We can include the step-by-step process, allowing integrators to test against the scenario.

2017-06-10 19:13 UTC, nbougalis commented on content/concept-partial-payments.md
> +The simplest and most effective way to avoid partial payment exploits is to use the `delivered_amount` field of the transaction metadata, not the `Amount` field, when processing incoming transactions
"processing incoming _payment_ transactions."

2017-06-13 01:03 UTC, mDuo13 commented
Opened https://github.com/ripple/ripple-dev-portal/pull/258 to address Nik's feedback.