Update Smart Contracts Use Case for style and consistency
XRPLF/xrpl-dev-portal pull request #2585
Opened 2024-05-14 14:32 UTC by DennisDawson

2024-06-14 17:07 UTC, amarantha-k requested changes
As noted in the comment, I think we need an alternative to the crow for escrow.

2024-06-14 17:07 UTC, amarantha-k commented on docs/img/uc-yescrow-holding-lock-and-key.png
The crow doesn't seem like the right illustration, but I don't have a good alternative in mind. Would defer this one to UX/design.

2024-06-14 17:10 UTC, amarantha-k commented on docs/img/uc-yescrow-holding-lock-and-key.png
Tagging @bugsbunnies for input.

2024-06-14 17:31 UTC, bugsbunnies commented on docs/img/uc-yescrow-holding-lock-and-key.png
Awesome illustrations! For the lock part, I would suggest making all the strokes of the lock green as well so both the lock and key stands out in green as highlighted items.

2024-06-14 17:35 UTC, bugsbunnies commented on docs/img/uc-yescrow-holding-lock-and-key.png
Would be good to also match the bird's eyes with the previous bird's eyes for consistency, they look slightly different.

2024-06-20 18:44 UTC, DennisDawson commented on docs/img/uc-yescrow-holding-lock-and-key.png
Fixed, thanks for the feedback. Still need to rethink the crow, though.

2024-06-20 20:41 UTC, DennisDawson commented on docs/img/uc-yescrow-holding-lock-and-key.png
Okay, a more apt metaphor, I reckon. The Escrow is a locker, the condition is a padlock, the fulfillment is the key.

2024-07-25 17:16 UTC, bugsbunnies approved these changes

2024-07-30 19:04 UTC, amarantha-k approved these changes
Thanks for incorporating the feedback.

2024-07-30 19:05 UTC, merged