Add new use cases logos and descriptions, fix use cases grid responsiveness
XRPLF/xrpl-dev-portal pull request #2630
Opened 2024-06-18 23:07 UTC by AKCodez

…nsiveness

2024-06-25 21:58 UTC, mDuo13 requested changes

2024-06-25 21:58 UTC, mDuo13 commented on static/js/modal.js
:tada: Love to see removal of unused code and assets!

2024-06-25 21:58 UTC, mDuo13 commented on static/img/uses/Zerpmon.png
The capital Z in this filename is causing the logo to not display.

2024-06-25 21:58 UTC, mDuo13 commented on styles/_use-cases.scss
> +      content: url("../img/uses/modallogos/threezy.png") !important;
The `!important` doesn't seem to do anything. It's bad practice to use `!important` where you can avoid it.

If it's not needed, can we remove it from here and also the light theme versions of the styles?

2024-06-25 22:20 UTC, AKCodez commented on static/img/uses/Zerpmon.png
Are you sure? Its displaying for me in both sections in light and dark mode

2024-06-26 03:26 UTC, mDuo13 commented on styles/light/_light-theme.scss
> +    content: url("../img/uses/lightmode/orchestra-finance.svg") !important;
Same as the above comment re: `!important` here too

2024-06-26 03:27 UTC, mDuo13 commented on static/img/uses/Zerpmon.png
Yes, it'll look OK in dev mode on Mac or Windows because their filesystems are not case-sensitive, but it won't be found when the host machine is uses a typical Linux filesystem like `ext4`.

2024-07-01 21:14 UTC, mDuo13 approved these changes
Fixed the `zerpmon.png` casing myself; rest should be good now. I'll resolve the conflicts with master (redocly 0.86 / css clashes) myself and merge it myself.

2024-07-01 21:21 UTC, closed without merging

2024-07-01 21:21 UTC, mDuo13 commented
Merged as 0845af6e46dffa1d421fc5e1510ad528746943ce