Update Clio install instructions
XRPLF/xrpl-dev-portal pull request #2669
Opened 2024-07-08 23:47 UTC by mDuo13

- Clarify nightly and release channels
- Mention self-contained binaries
- Update build from source and default config file links
- Update to reflect that `clio` package now only installs the Clio server; the "all-in-one" package that installs both `rippled` and Clio is no longer supported.
- Fix step numbering and admonition syntax

2024-07-10 23:41 UTC, godexsoft requested changes
Found a few small things to adjust, looks good otherwise 🙇

2024-07-10 23:41 UTC, godexsoft commented on docs/infrastructure/installation/install-clio-on-ubuntu.md
> +- [Build Clio from source](https://github.com/XRPLF/clio/blob/develop/docs/build-clio.md).
Maybe worth mentioning that we now also produce docker images: https://hub.docker.com/r/rippleci/clio

2024-07-10 23:41 UTC, godexsoft commented on docs/infrastructure/installation/install-clio-on-ubuntu.md
>  -  You need compatible versions of CMake and Boost. Clio requires C++20 and Boost 1.75.0 or higher.
Clio requires C++23 and Boost 1.83.0 or higher. More info here: https://github.com/XRPLF/clio/blob/develop/docs/build-clio.md

2024-07-12 16:40 UTC, oeggert approved these changes
Looks good to me besides a couple minor points.

2024-07-12 16:40 UTC, oeggert commented on docs/infrastructure/installation/install-clio-on-ubuntu.md
> +-  You need compatible versions of CMake and Boost. Clio requires C++23 and Boost 1.83.0 or higher.
```suggestion
-  Clio requires C++23 and Boost 1.83.0 or higher.
```
Nitpick: just say the requirement.

2024-07-12 16:40 UTC, oeggert commented on docs/infrastructure/installation/install-clio-on-ubuntu.md
> +        You can use multiple `rippled` servers as a data source by add more entries to the `etl_sources` section. If you do, Clio load balances requests across all the servers in the list, and can ke
```suggestion
        You can use multiple `rippled` servers as a data source by adding more entries to the `etl_sources` section. If you do, Clio load balances requests across all the servers in the list, and can keep up with the network as long as at least one of the `rippled` servers is synced.
```

2024-07-19 19:22 UTC, merged