adds new institutional defi page
XRPLF/xrpl-dev-portal pull request #2848
Opened 2024-11-11 18:32 UTC by AKCodez

2024-11-15 18:56 UTC, amarantha-k reviewed
A few comments:
- Could you move the page under Tokenization, so the URL would be /docs/use-cases/tokenizaton/ ?
- Could we rename the page to "real-world-assets-tokenization"?

2024-11-19 22:16 UTC, Calvinjwala approved these changes
LGTM!

2024-11-19 23:50 UTC, mDuo13 requested changes
Mostly looks good but I noticed a couple small things I'd like to see fixed before merging.

2024-11-19 23:50 UTC, mDuo13 commented on styles/_contribute.scss
> +                        color: #9A52FF;
This is a color we have defined in `_colors.scss` so let's use the variable instead of having another random constant:

```suggestion
                        color: $blue-purple-400;
```

2024-11-19 23:50 UTC, mDuo13 commented on docs/use-cases/tokenization/real-world-assets.page.tsx
> +    title: "RWA Tokenization on XRP Ledger",
This title could use some work. "RWA" is jargon that people may not know—even in the finance space, it could mean "risk-weighted assets" for example. And we don't need to emphasize "on XRP Ledger" when this whole _site_ is about the XRP Ledger.

See screenshot for how it seems to stand out:

![2024-11-19_142621_435106233](https://github.com/user-attachments/assets/4fc9cc3a-2324-4998-b379-803ecce72946)


```suggestion
    title: "Real-World Asset Tokenization",
```

2024-11-19 23:50 UTC, mDuo13 commented on docs/use-cases/tokenization/real-world-assets.page.tsx
> +    link: "https://xrpl.org/docs/tutorials/how-tos/use-tokens/issue-a-fungible-token",
Using a fully-specified URL here means that viewers of the translated site will get shunted to the English-language version of the site when they click it.

It's possible to make it work the intended way, but you need to do two things:

1. Use an absolute path here, e.g.

    ```suggestion
        link: "/docs/tutorials/how-tos/use-tokens/issue-a-fungible-token",
    ```
    (NOTE: If you use my commit below, it modifies these lines already so you don't need to use this suggestion separately.)
2. Change the `FeatureItem` definition below to use a `<Link>` element rather than an `onclick` handler.

2024-11-19 23:50 UTC, mDuo13 commented on docs/use-cases/tokenization/real-world-assets.page.tsx
> +    </li>
It's bad practice to use `onclick` when all you want is something that works like a link—it breaks behavior in subtle ways, like middle-clicking won't open it in a new tab and SEO doesn't catch things.

But furthermore, this whole component is re-creating one we already have defined. I've adjusted the shared component and refactored this page to use it here: 6835e174b42f5d4c84ea810670f0185d670b4c5e . Feel free to pull that commit and use it.

2024-11-20 00:29 UTC, amarantha-k commented on docs/use-cases/tokenization/real-world-assets.page.tsx
> +    title: "RWA Tokenization on XRP Ledger",
This was a recommendation for SEO - "RWA Tokenization on XRP Ledger" for the title and "real-world-assets" for the page name.

2024-11-20 00:32 UTC, amarantha-k commented
Other than the page title which was recommended for SEO, agree that it would be good to fix the rest of the comments by @mDuo13 before merging this PR.

2024-11-20 01:49 UTC, mDuo13 approved these changes

2024-11-20 02:16 UTC, amarantha-k approved these changes
Thanks for incorporating the feedback. LGTM!

2024-11-20 17:14 UTC, merged