Checks Tutorials
XRPLF/xrpl-dev-portal pull request #329
Opened 2018-04-03 01:38 UTC by mDuo13

Includes currently-viable instructions for many Checks tasks, although several may need to change slightly as rippled and ripple-lib are updated. (Those changes are noted as TODOs in comments.)

Does not include a comprehensive suite of examples (JSON-RPC, WebSocket, etc.) for every step because that's a _lot_ of work. I've tried to include at least RippleAPI and Commandline examples for most steps and could probably add JSON-RPC easily enough (since the responses are basically just the Commandline ones). I don't have a commandline example for account_objects and maybe should (it's a slightly inconvenient one since you have to use the `json` method instead of the native `account_objects` commandline syntax to get  filtering by type)

Includes minor changes to the Regular Keys tutorial (pulling out some snippets for reuse) and moves the Checks concept's place in the Dactyl config file to match the Enterprise doc plan outline (even though this will probably change again later per the information architecture).

2018-04-03 22:24 UTC, scottschurr approved these changes
Nice work.  I did note a small number of copy-and-paste-os the you will probably want to address. :+1:

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +| `SendMax`         | String or Object (Amount) | The maximum amount the sender can be debited when this Check gets cashed. For XRP, use a string representing drops of XRP. For issued currencies, use
It's all good and I particularly like the last sentence. :+1:

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +| `TransactionType` | String                    | The value `CheckCancel` indicates this is a CheckCancel transaction. |
Copy-and-paste-o.  Should be `CheckCash` in two places.

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +| `Account`         | String (Address)          | The address of the sender who is canceling the Check. (In other words, your address.) |
canceling -> cashing

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +| `CheckID`         | String                    | The ID of the Check object in the ledger to cancel. You can get this information by looking up the metadata of the CheckCreate transaction using the
cancel -> cash

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +| `Amount`          | String or Object (Amount) | The amount to redeem from the Check. For XRP, this must be a string specifying drops of XRP. For issued currencies, this is an object with `currency`
Seems like it's worth mentioning somewhere (not necessarily here) that, when cashing a Check, specifying the Amount from the Check object may not be successful.  That could happen because the currency issuer has a transfer fee.  It could also happen if the writer of the Check has insufficient funds.

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +| `TransactionType` | String                    | The value `CheckCancel` indicates this is a CheckCancel transaction. |
CheckCancel -> CheckCash twice

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +| `Account`         | String (Address)          | The address of the sender who is canceling the Check. (In other words, your address.) |
canceling -> cashing

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +| `CheckID`         | String                    | The ID of the Check object in the ledger to cancel. You can get this information by looking up the metadata of the CheckCreate transaction using the
cancel -> cash

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +| `DeliverMin`      | String or Object (Amount) | A minimum amount to receive from the Check. If you cannot receive at least this much, cashing the Check fails, leaving the Check in the ledger so you
It's all good, but I especially like the second sentence.

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +| `tecEXPIRED` | The Check has expired. | Cancel the Check and ask the sender to create a new Check with a later Expiration time. |
Nice table!

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +    For example, the following `ModifiedNode` shows that the the account rGPnRH1EBpHeTF2QG8DCAgM7z5pb75LAis, the Check's recipient and the sender of this CheckCash transaction, had its XRP balance ch
"the the" -> "the"

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +    The net amount of 99.99999 XRP includes deducting the transaction cost is destroyed to pay for sending this CheckCash transaction. The following transaction instructions (excerpted) show that the
The first sentence reads funny, "...deducting the transaction cost is destroyed...".  Maybe "... cost _that_ is ..."?

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +  if (check_object.Account == recipient_address) {
Should this be `check_object.Destination == recipient_address`?

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +| `Amount`          | String or Object (Amount) | The amount to redeem from the Check. For XRP, this must be a string specifying drops of XRP. For issued currencies, this is an object with `currency`
In the `DeliverMin` field description, below, you say something like, "If you cannot receive this much, cashing the Check fails, leaving the Check in the ledger so you can try again."  I think that would be a great addition here as well.

2018-04-03 22:24 UTC, scottschurr commented on content/tutorial-checks.md
> +If cashing the Check failed, the Check remains in the ledger so you can try cashing again later. You may want to [cash the Check for a flexible amount](#cash-a-check-for-a-flexible-amount) instead.
I like this sentence.  I wonder if there's a good place for a comparable sentence in the **Confirm final result** section of **Cash a Check for a flexible amount**?

2018-04-04 23:41 UTC, ryangyoung requested changes
This content is great and, I know, the result of a lot of hard and sometimes frustrating work. It's wonderful that we have working examples for all of the permutations of sending and cashing checks. This is a framework that we can modify and build on, and, in some ways can serve as a model. 

That said...a lot of the material reads very similarly to a reference. It's awesome that there are specific example requests and responses for each possible permutation. But, because a lot of the examples cover so much information and caveats, I worry that a user who _just_ wants to figure out how to send a check will end up lost in some of the details that may be better housed in the reference. I think this can be addressed by two hopefully not too onerous changes:

* Split up each tutorial into its own file. Currently, it's very long. I think a better user experience would be to have each tutorial (send, look up checks, cash checks for exact amount, etc) on a separate, short page. That provides at least an illusion of simplicity. And the more flexible nesting planned for Dactyl will make it easier to discover the possible next steps. 

* Add an example scenario that provides some kind of use case (tied if possible to one of our top-level personas and/or use cases). That way, it's clear to a user that, "hey, I could use this to fulfill an invoice!" (or whatever). A scenario that unfolds across each separate tutorial would be especially helpful (i.e., Alice prepares checkCreate tx to Bob for widget delivery, Alice submits CheckCreate transaction, Bob looks up checks to him, Alice looks up status of checks, Bob cashes check for exact amount, Bob cashes another check from Alice for a flexible amount).

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +Checks in the XRP Ledger are similar to paper personal checks. This tutorial steps through the following processes for using Checks:
This might be a good place to add a link the conceptual article.

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +Checks in the XRP Ledger are similar to paper personal checks. This tutorial steps through the following processes for using Checks:
This, or within the tasks themselves, might also be a good place to provide a brief use-case like statement. _Why_ would I want to do these things?

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +Checks in the XRP Ledger are similar to paper personal checks. This tutorial steps through the following processes for using Checks:
A bit of a stretch and something that would involve more work, but it would be really cool to see all of these tasks tied together by a sort of pseudo-narrative that explains the "why" for each task. For example, BobCo did some crypto consulting work for AliceCo and to fulfill the invoice they received, AliceCo wants to send a check to BobCo's account at Acme Credit Union, which has deposit auth enabled. (It would be _really_ cool to tie the narrative to one of our known use cases, but that's probably even more of a stretch.)

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +Sending a Check involves sending a [CheckCreate transaction][], which creates a [Check object in the ledger](reference-ledger-format.html#check). Most of the fields of a CheckCreate transaction are s
This is great, but, again, it would be great to see at least a brief explanation of why I'd want to do this. (Also, this is mostly covered in the concept article, though without a few of the details here. So I'd question if we want to reiterate that content here. In other words, if I wanted to understand how it works, the concept is where I'd look.)

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +### Prerequisites
Are these prerequisites for all of the tasks in this topic? If so, I'd suggest moving this section up a level since you need these things do the rest of the steps, not just sending a check.

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +    - You can use the [XRP Ledger Test Net Faucet](https://ripple.com/build/xrp-test-net/) to get a funded address and secret with 10,000 Test Net XRP.
This is great. Would it also be worth linking to `wallet_create` and whatever other methods you'd need to do the same on the production network... oh, when Checks is enabled there. Never mind.

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +Decide how much money the Check is for and who can cash it. Figure out the values of the [CheckCreate transaction][] fields. The following fields are the bare minimum; everything else is either optio
Especially for a tutorial, I think it would help the user to provide an arbitrary amount (whatever's in the example) and receiver (e.g. BobCo) here. Basically, another appeal for the use case/narrative thread.

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +Decide how much money the Check is for and who can cash it. Figure out the values of the [CheckCreate transaction][] fields. The following fields are the bare minimum; everything else is either optio
The following table is, I think, already in the reference. I know this version is listing only the bare minimum fields, but I wonder if we or want to recreate it here. One goal of tutorials, I think, is to try to make things _seem_ easier (without sacrificing accuracy, of course).

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +| `TransactionType` | String                    | The value `CheckCreate` indicates this is a CheckCreate transaction. |
If we do keep the table here, I think the description fields should be more targeted toward the user. As a user, I'd ask: so, is `CheckCreate` what I should use here, or what? The existing language seems better suited to reference material.

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +| `Account`         | String (Address)          | The address of the sender who is creating the Check. (In other words, your address.) |
Another place where some example value would really help a user new to Checks.

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +| `Destination`     | String (Address)          | The address of the intended recipient who can cash the Check. |
Again, an example value (like BobCo) would be great here.

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +| `SendMax`         | String or Object (Amount) | The maximum amount the sender can be debited when this Check gets cashed. For XRP, use a string representing drops of XRP. For issued currencies, use
Agree with Scott on both points. I think an example scenario would really clarify that caveat, too.

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +#### Example CheckCreate Preparation
Nit: since this is a tutorial, how about rephrasing this to something like  "Example: Prepare CheckCreate Transaction"

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +#### Example CheckCreate Preparation
Ah, I see. This makes more sense in the generated doc.

2018-04-04 23:41 UTC, ryangyoung commented on content/tutorial-checks.md
> +### {{send_n.next()}}. Submit the signed transaction
To beat what may at this point already be a dead horse, the text in the include reads more like a reference than a tutorial. Again, as a user, I might ask something like, "OK, cool. What do _I_ do now?"

2018-04-05 22:09 UTC, mDuo13 commented on content/tutorial-checks.md
> +    The net amount of 99.99999 XRP includes deducting the transaction cost is destroyed to pay for sending this CheckCash transaction. The following transaction instructions (excerpted) show that the
Yeah, I waffled between "cost destroyed" and "cost that is destroyed" and ended up at a completely unreasonable compromise. ;)

2018-04-05 22:12 UTC, mDuo13 commented on content/tutorial-checks.md
> +If cashing the Check failed, the Check remains in the ledger so you can try cashing again later. You may want to [cash the Check for a flexible amount](#cash-a-check-for-a-flexible-amount) instead.
The equivalent sentence when you're already cashing for a flexible amount is in the "Handling Errors" section:

> If cashing the Check failed with a `tec`-class code, look up the code in the [Full Transaction Response List] and respond accordingly.

2018-04-06 23:01 UTC, ryangyoung commented on content/snippets/checkcash-prereqs.md
> +- You need the ID of a Check object currently in the ledger.
Nit: for readability, add at least one line between each item in the list.

2018-04-06 23:02 UTC, ryangyoung commented on content/tutorial-checks.md
> +In many cases, you want to send a [Payment][] instead of a Check, since that delivers the money directly to the recipient in one step. However, if your intended recipient uses [DepositAuth](concept-d
🙌

2018-04-06 23:07 UTC, ryangyoung approved these changes

2018-04-06 23:15 UTC, ryangyoung commented
I haven't built this locally, but it looks like each section of the tutorial was broken up into its own section, which should improve the user experience. That addresses my first major point. 

The second major point, about adding some kind of through-line scenario or use case was somewhat addressed with the addition of some language about why a user would want to send or cancel a check. That's great. I think we could extend that even further, though, and for that, I added https://ripplelabs.atlassian.net/browse/DOC-1380 (Ripple employees only).  But as far as I'm concerned, this is good to publish for now. We can add the use case stuff later.

2018-04-09 20:37 UTC, merged