Fix transaction results landing page
XRPLF/xrpl-dev-portal pull request #392
Opened 2018-05-16 21:26 UTC by jhaaaa

- Moved content on transaction-results.md to transaction-results-overview.md
- Deleted transaction-results.md
- Added blurbs for child pages in dactyl_config

2018-05-16 23:22 UTC, mDuo13 requested changes
This is one case where I'm not 100% convinced that adding a separate "overview" page is helpful. 

With how many pages link to `transaction-results.html`, I think I'd rather that file display the "Overview" contents, complete with the provisional/final codes warning.

I'm willing to be convinced otherwise, especially since we so rarely put important content on landing pages, but given that this is a "sub-page" rather than a category page, I feel like the issue is less pressing.

2018-05-16 23:22 UTC, mDuo13 commented on dactyl-config.yml
> +        blurb: tec codes indicate that the transaction failed, but it was applied to a ledger to apply the transaction cost.
Suggestion: Instead of "applied to a ledger to apply the transaction cost" how about "applied to a ledger to deduct the transaction cost"? or maybe "included in a ledger to apply the transaction cost"?

(Yes, I realize the subpar original wording comes straight from the tec-codes file; in other words, it's my own fault. Sorry.)

2018-05-16 23:22 UTC, mDuo13 commented on content/references/rippled-api/transaction-formats/transaction-results/transaction-results-overview.md
> +| Claimed cost only     | [tec](tec-codes.html)   | The transaction did not achieve its intended purpose, but the [transaction cost](transaction-cost.html) was destroyed. This result is only final in
I think the original ordering here was from least likely to most likely to succeed, or something along those lines? It wasn't exactly useful, so the alphabetical ordering you've switched it to is an improvement. :+1:

2018-05-17 00:18 UTC, jhaaaa commented
Thank you for the thoughtful review, @mDuo13! I've made the changes we discussed. Ready for review at your convenience.

2018-05-17 01:28 UTC, mDuo13 approved these changes

2018-05-18 18:24 UTC, merged