Update ubuntu build steps
XRPLF/xrpl-dev-portal pull request #440
Opened 2018-08-02 06:37 UTC by jacksteroo

- consolidated initial install dependencies
- BOOST_ROOT dir will be incorrectly set if your username is not ubuntu
- automatically setting number of processors to use to compile Boost libraries to half of what users would have
- git log to now show v1.0.1
- numbering changes

2018-08-02 23:45 UTC, mDuo13 requested changes
I like the changes you've made here, except for setting the processors automatically. (Having guidance of using `/proc/cpuinfo` is a good idea, but the grep and line count are too fragile for my tastes.) If you can remove that part of the changes, I'd like to merge this and rebase #439 on it.

2018-08-02 23:45 UTC, mDuo13 commented on content/tutorials/manage-the-rippled-server/build-run-rippled-ubuntu.md
> +              PROCESSORS=$(expr "`grep processor /proc/cpuinfo | wc -l`" / 2)
I'd rather not have a tricky mini-script like this in the instructions; it could return incorrect values due to unrelated factors like "processor" being added to other lines of the output. For example, the model name, flags, and bugs lines contain a bunch of arbitrary strings; it wouldn't be that surprising if one of them happened to contain the substring `processor` in the future, causing the grep to miscount.

2018-08-02 23:45 UTC, mDuo13 commented on content/tutorials/manage-the-rippled-server/build-run-rippled-ubuntu.md
> +        commit 8429dd67e60ba360da591bfa905b58a35638fda1
Gonna change this again when 1.1.0 comes out (very soon), but it's fine for now.

2018-08-03 21:24 UTC, mDuo13 commented
Incorporated into #439.

2018-08-03 21:24 UTC, closed without merging

2018-08-07 06:41 UTC, jacksteroo commented on content/tutorials/manage-the-rippled-server/build-run-rippled-ubuntu.md
> +              PROCESSORS=$(expr "`grep processor /proc/cpuinfo | wc -l`" / 2)
The regex could be tightened up a bit to look like this:

              PROCESSORS=$(expr `grep "processor\s:\s[0-9]\+" /proc/cpuinfo | wc -l` / 2)

Looks like most of the changes are consolidated into #439.  Either ways, glad to help.