Direct XRP Payments article
XRPLF/xrpl-dev-portal pull request #626
Opened 2019-07-16 22:49 UTC by mDuo13

- Adds new concept article on direct XRP-to-XRP payments
- Moves some source & destination tags content out of the gateway guide.
- Renames "complex payment types" to "payment types" (in concepts) and renames "Use complex payment types" to "Use specialized payment types" (in tutorials)
    - Leaves redirect pages for both old file names.
- Adds a table to the Payment transaction type reference describing different uses for the Payment transaction type

2019-07-17 15:51 UTC, ximinez requested changes

2019-07-17 15:51 UTC, ximinez commented on content/concepts/payment-types/direct-xrp-payments.md
> +    - Confirming that the destination is different than the sender.
Since we're talking about tags, I think it would be helpful to add a note here emphasizing that different source and destination tags for the same account are not sufficient to meet this criteria.

2019-07-17 15:51 UTC, ximinez commented on content/tutorials/manage-account-settings/require-destination-tags.md
> +```
You've got different values for `SetFlag` in the example request and response. That shouldn't ever happen. `asfRequireDest` is 1.

2019-07-18 16:49 UTC, pgarg-ripple approved these changes
LGTM

2019-07-18 19:49 UTC, merged