Add consensus stream documentation
XRPLF/xrpl-dev-portal pull request #743
Opened 2019-12-06 03:26 UTC by movitto

Documentation pertaining to the newly added consensus stream (rippled 1.4.0)

2019-12-09 22:19 UTC, mDuo13 commented
!rebuild

2019-12-09 22:23 UTC, mDuo13 requested changes
Thank you for adding this. I left a couple small suggestions I'd like to see applied before we merge this. Everything else looks great!

2019-12-09 22:23 UTC, mDuo13 commented on content/references/rippled-api/public-rippled-methods/subscription-methods/subscribe.md
> +| `consensus`         | String                    | The new consensus phase the server is in, one of 'open', 'establish', or 'accepted'.|
Please change the description to the following:

> The new consensus phase the server is in. Possible values are `open`, `establish`, and `accepted`.

And please make sure there is a space before the closing `|`.

Also, I'd love to have descriptions of how those states correspond to the steps described in the [Consensus article](https://xrpl.org/consensus.html) but we can push this first and add those later.

2019-12-09 22:23 UTC, mDuo13 commented on content/references/rippled-api/public-rippled-methods/subscription-methods/subscribe.md
> +The `consensus` stream sends `consensusPhase` messages when [the consensus process](consensus.html) changes phase. The message contains the new phase of consensus the server is in.
Please add `[New in: rippled 1.4.0][]` to the end of this line.

2019-12-10 12:58 UTC, movitto commented
@mDuo13 made the requested changes. Since this is a small commit I didn't bother with the [FOLD] and just force pushed the single patch. Also to keep it consistent w/ the "Validations Stream" section above I put the "[New in: rippled 1.4.0][]" below the "Consensus Stream" header but above the description. If the original way you suggested is desired please just mention and I'll change it to that.

Thank you for reviewing

2019-12-11 23:29 UTC, mDuo13 approved these changes

2019-12-11 23:29 UTC, merged