Add warning about failed AccountDelete costs
XRPLF/xrpl-dev-portal pull request #851
Opened 2020-06-02 09:54 UTC by mDuo13

Fixes #850.

Note, due to the nature of consensus, `fail_hard` is not a failsafe guarantee that the transaction won't be validated with a `tec` code, but it prevents the vast majority of cases.

2020-06-02 16:10 UTC, ximinez requested changes

2020-06-02 16:10 UTC, ximinez commented on content/concepts/payment-system-basics/accounts/accounts.md
> +**Warning:** The [AccountDelete transaction][]'s transaction cost applies even if the transaction fails because the account does not meet the requirements to be deleted. To avoid paying 5 XRP in case
Suggestion:

**Warning**: The [AccountDelete transaction][]'s cost applies if the transaction is properly structured and signed, but the account does not meet the requirements to be deleted. [Submit the transaction](submit.html) with `fail_hard` enabled to lower the chances of paying the high transaction fee if the account is not deletable when the transaction is validated.

2020-06-03 20:57 UTC, mDuo13 commented
Rebased on master to get some broken link fixes, reworded the sentence @ximinez pointed out, and added a similar warning to the AccountDelete tx reference page.

2020-06-03 21:26 UTC, ximinez approved these changes
I had another thought, but I'm not going to hold up this change if you don't think it's worth it.

2020-06-03 21:26 UTC, ximinez commented on content/concepts/payment-system-basics/accounts/accounts.md
> +**Warning:** The [AccountDelete transaction][]'s transaction cost always applies when the transaction is included in a validated ledger, even if the transaction failed because the account does not me
Would it be worth mentioning the `"deletion_blockers_only" : "true"` to the `account_objects` method here?

2020-06-03 22:12 UTC, MarkusTeufelberger commented
Maybe also mention how to check each requirement with the respective API calls?

2020-06-05 23:12 UTC, mDuo13 commented
I would like to add a more detailed tutorial with step-by-step instructions on deleting your account, including how to check the requirements, etc., but I think that's a bigger scope and should not hold up this PR.

2020-06-05 23:45 UTC, mDuo13 commented
The broken links are some kind of GitHub or link checker glitch. The links from this PR work.

2020-06-05 23:45 UTC, merged