refactor: remove duplicated  word
XRPLF/xrpl-dev-portal pull request #888
Opened 2020-08-24 12:13 UTC by alexprut

Self explanatory.

2020-08-24 18:32 UTC, mDuo13 requested changes
This is not actually a typo, but is just an [awkward sentence in English](https://english.stackexchange.com/a/3426).

I've suggested a change that I think makes it read a little more naturally while maintaining the intended meaning.

2020-08-24 18:32 UTC, mDuo13 commented on content/concepts/consensus-network/amendments/known-amendments.ja.md
> +the latest ledger that validator considers to be fully validated. The consensus process can use this information to increase the robustness of consensus.
```suggestion
the latest ledger that the validator considers to be fully validated. The consensus process can use this information to increase the robustness of consensus.
```

2020-08-24 18:32 UTC, mDuo13 commented on content/concepts/consensus-network/amendments/known-amendments.md
> +the latest ledger that validator considers to be fully validated. The consensus process can use this information to increase the robustness of consensus.
```suggestion
the latest ledger that the validator considers to be fully validated. The consensus process can use this information to increase the robustness of consensus.
```

2020-08-25 10:21 UTC, alexprut commented
@mDuo13 thanks for the feedback, I've applied the suggested changes.

2020-08-27 10:59 UTC, alexprut commented
@mDuo13 please let me know if you wanna proceed with this change, otherwise feel free to close this pr.

2020-09-01 07:02 UTC, merged